<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/password/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Password plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-password/
*/
$labels['changepasswd']  = 'Ndrysho fjalëkalimin';
$labels['curpasswd']  = 'Fjalëkalimi i Tanishëm';
$labels['newpasswd']  = 'Fjalëkalimi i Ri:';
$labels['confpasswd']  = 'Konfirmoni fjalëkalimin e ri:';
$messages['nopassword'] = 'Ju lutemi, futni fjalëkalimin e ri.';
$messages['nocurpassword'] = 'Ju lutemi, futni fjalëkalimin e tanishëm.';
$messages['passwordincorrect'] = 'Fjalëkalimi i tanishëm është i pasaktë.';
$messages['passwordinconsistency'] = 'Fjalëkalimet nuk përputhen, ju lutemi, riprovoni.';
$messages['crypterror'] = 'S’u ruajt dot fjalëkalimi i ri. Mungon funksioni i Fshehtëzimit.';
$messages['connecterror'] = 'S’u ruajt dot fjalëkalimi i ri. Gabim lidhjejej.';
$messages['internalerror'] = 'S’u ruajt dot fjalëkalimi i ri.';
$messages['passwordshort'] = 'Fjalëkalimi duhet të jetë të paktën $length shenja i gjatë.';
$messages['passwordweak'] = 'Fjalëkalimi duhet të përmbajë të paktën një numër dhe një shenjë pikësimi.';
$messages['passwordforbidden'] = 'Fjalëkalimi përmban shenja të ndaluara.';
$messages['firstloginchange'] = 'Kjo është hyrja juaj e parë. Ju lutemi, ndryshoni fjalëkalimin tuaj.';
$messages['disablednotice'] = 'Sistemi është hëpërhë nën gjendje punimesh mirëmbajtjeje dhe ndryshimi i fjalëkalimit s’është i mundur në këtë çast. Gjithçka do të duhej të ish kthyer në gjendje normale shumë shpejt. Kërkojmë ndjesë për çfarëdo siklet.';
$messages['passwinhistory'] = 'Ky fjalëkalim është përdorur një herë më parë.';
$messages['samepasswd'] = 'Fjalëkalimi i ri duhet të  jetë i ndryshëm nga i vjetri.';
$messages['passwdexpirewarning'] = 'Kujdes! Fjalëkalimi juaj do të skadojë së shpejti, ndryshojeni para $expirationdatetime.';
$messages['passwdexpired'] = 'Fjalëkalimi juaj ka skaduar, lypset ta ndryshoni tani!';
