#! /bin/bash
set -e

while ! mysqladmin ping --host mysql -u${DBUSER} -p${DBPASS} --silent; do
  echo "Waiting for database to come up..."
  sleep 2
done

while [[ -z ${MM_DB} ]]; do
  MM_DB=$(mysql -h mysql-mailcow -u ${DBUSER} -p${DBPASS} ${DBNAME} -e "SHOW DATABASES LIKE '%_mm'" -Bs)
  [[ -z ${MM_DB} ]] && sleep 3
done

echo "# This file is autogenerated at container startup." > /etc/mailman.cfg

cat >> /etc/mailman.cfg <<EOF
[mta]
incoming: mailman.mta.postfix.LMTP
outgoing: mailman.mta.deliver.deliver
lmtp_host: mm-core
lmtp_port: 8024
smtp_host: postfix
smtp_port: 588
configuration: /etc/postfix-mailman.cfg

[runner.retry]
sleep_time: 10s

[webservice]
hostname: mm-core
admin_user: restadmin
admin_pass: $(echo -n ws_${DBPASS}_${MAILCOW_HOSTNAME} | sha3sum | cut -d ' ' -f1)

[database]
class: mailman.database.mysql.MySQLDatabase
url: mysql+pymysql://${DBUSER}:${DBPASS}@mysql/${DBNAME}_mm

[archiver.hyperkitty]
class: mailman_hyperkitty.Archiver
enable: yes
configuration: /etc/mailman-hyperkitty.cfg
EOF

cat > /etc/mailman-hyperkitty.cfg <<EOF
[general]
base_url: http://mm-web:8000/hyperkitty
api_key: $(echo -n hk_${DBPASS}_${MAILCOW_HOSTNAME} | sha3sum | cut -d ' ' -f1)
EOF

cat > /etc/postfix-mailman.cfg <<EOF
[postfix]
transport_file_type: regex
postmap_command: true
EOF

if [[ -e /opt/extra-mailman/mailman-extra.cfg ]]; then
  echo "Found configuration file at /opt/mailman/mailman-extra.cfg"
  cat /opt/extra-mailman/mailman-extra.cfg >> /etc/mailman.cfg
fi

chown -R mailman /opt/mailman

su-exec mailman mailman aliases

exec "$@"
