  - package-ecosystem: docker
    directory: "/data/Dockerfiles"
    schedule:
      interval: daily
      time: "04:00"
    target-branch: "staging"
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 10
