---
kind: pipeline
name: integration-testing

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:

- name: download-tests
  pull: default
  image: timovibritannia/ansible
  commands:
  - git clone https://github.com/mailcow/mailcow-integration-tests.git --branch $(curl -sL https://api.github.com/repos/mailcow/mailcow-integration-tests/releases/latest | jq -r '.tag_name') --single-branch .
  - wget -O group_vars/all/secrets.yml $SECRETS_DOWNLOAD_URL --quiet
  environment:
    SECRETS_DOWNLOAD_URL:
      from_secret: SECRETS_DOWNLOAD_URL
  when:
    branch:
    - master
    event:
    - push

- name: lint
  pull: default
  image: timovibritannia/ansible
  commands:
  - ansible-lint ./
  when:
    branch:
    - master
    event:
    - push

- name: create-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - chmod +x ci.sh
  - ./ci.sh
  - ansible-playbook mailcow-start-server.yml --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
    VAULT_PW:
      from_secret: VAULT_PW
  when:
    branch:
    - master
    event:
    - push

- name: setup-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - chmod +x ci.sh
  - ./ci.sh
  - sleep 120
  - ansible-playbook mailcow-setup-server.yml --private-key /drone/src/id_ssh_rsa --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
    VAULT_PW:
      from_secret: VAULT_PW
  when:
    branch:
    - master
    event:
    - push

- name: run-tests
  pull: default
  image: timovibritannia/ansible
  commands:
  - chmod +x ci.sh
  - ./ci.sh
  - ansible-playbook mailcow-integration-tests.yml --private-key /drone/src/id_ssh_rsa --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
    VAULT_PW:
      from_secret: VAULT_PW
  when:
    branch:
    - master
    event:
    - push

- name: delete-server
  pull: default
  image: timovibritannia/ansible
  commands:
  - chmod +x ci.sh
  - ./ci.sh
  - ansible-playbook mailcow-delete-server.yml --diff
  environment:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_FORCE_COLOR: true
    VAULT_PW:
      from_secret: VAULT_PW
  when:
    branch:
    - master
    event:
    - push
    status:
    - failure
    - success
---
kind: signature
hmac: d0ded978bd57646ae10307a3e7fd6584658e285929596ad1ee391cf7330d6338

...
