<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Настана грешка!';
$messages['loginfailed']  = 'Најавата не успеа';
$messages['cookiesdisabled'] = 'Вашиот прелистувач не прифаќа колачиња';
$messages['sessionerror'] = 'Сесијата е неважечка или е истечена';
$messages['storageerror'] = 'Поврзувањето со IMAP не успеа';
$messages['servererror'] = 'Грешка во серверот!';
$messages['servererrormsg'] = 'Грешка со серверот: $msg';
$messages['accountlocked'] = 'Премногу обиди за најава. Пробајте повторно подоцна.';
$messages['connerror'] = 'Грешка со конекција (Неуспешно конектирање со серверот)!';
$messages['dberror'] = 'Грешка со датабазата!';
$messages['windowopenerror'] = 'Popup прозорецот беше блокиран!';
$messages['requesttimedout'] = 'Сесијата за барањето истече';
$messages['errorreadonly'] = 'Операцијата неможе да се изврши. Папката може само да се прегледува.';
$messages['errornoperm'] = 'Операцијата неможе да се изврши. Немате доволно пермисии.';
$messages['erroroverquota'] = 'Операцијата неможе да се изврши. Нема слободно место.';
$messages['erroroverquotadelete'] = 'Немате повеќе слободно место. Користете SHIFT+DEL да избришете порака.';
$messages['invalidrequest'] = 'Неважечко барање! Податоците не се зачувани.';
$messages['invalidhost'] = 'Името на серверот не е валидно.';
$messages['nomessagesfound'] = 'Немате писма во ова сандаче';
$messages['loggedout'] = 'Успешно се одјавивте. Ви благодариме и довидување!';
$messages['mailboxempty'] = 'Поштенското сандаче е празно.';
$messages['nomessages'] = 'Нема пораки';
$messages['refreshing'] = 'Освежување...';
$messages['loading'] = 'Вчитувам...';
$messages['uploading'] = 'Ја подигам податотеката...';
$messages['attaching'] = 'Датотеката се прикачува...';
$messages['uploadingmany'] = 'Датотеките се прикачуваат...';
$messages['loadingdata'] = 'Ги вчитувам податоците...';
$messages['checkingmail'] = 'Проверувам нова пошта...';
$messages['sendingmessage'] = 'Ја испраќам пораката...';
$messages['messagesent'] = 'Пораката е успешно испратена';
$messages['savingmessage'] = 'Ја зачувувам пораката...';
$messages['messagesaved'] = 'Пораката е зачувана во Непратени';
$messages['successfullysaved'] = 'Успешно зачувано';
$messages['savingresponse'] = 'Одговорот се снима...';
$messages['deleteresponseconfirm'] = 'Избриши го одговорот?';
$messages['addedsuccessfully'] = 'Името е успешно додадено во Именикот';
$messages['contactexists'] = 'Контакт со иста адреса на Е-пошта веќе постои.';
$messages['contactnameexists'] = 'Контакт со истото име веќе постои.';
$messages['blockedimages'] = 'За да се заштити вашата приватност, сликите во оваа порака не се прикажани.';
$messages['encryptedmessage'] = 'Оваа порака е кодирана и не може да се прикаже. Жалиме!';
$messages['nocontactsfound'] = 'Нема пронајдено имиња.';
$messages['contactnotfound'] = 'Бараното име не е пронајдено';
$messages['contactsearchonly'] = 'Внесете според што да се пребаруваат контактите.';
$messages['sendingfailed'] = 'Не упеав да го испратам писмото';
$messages['senttooquickly'] = 'Почекајте $sec секунда/и пред да го испратите писмото';
$messages['errorsavingsent'] = 'Се случи грешка при снимањето на испратената порака.';
$messages['errorsaving'] = 'Се случи грешка при снимањето.';
$messages['errormoving'] = 'Не можев да го преместам писмото';
$messages['errorcopying'] = 'Пораката (пораките) не е успешно ископрана.';
$messages['errordeleting'] = 'Не можев да го избришам писмото';
$messages['errormarking'] = 'Не можев да го обележам писмото';
$messages['deletecontactconfirm']  = 'Дали сте сигурни дека сакате да го избришете одбраното(те) име(ња)?';
$messages['deletegroupconfirm']  = 'Избриши ја изберената група?';
$messages['deletemessagesconfirm'] = 'Дали сте сигурни дека сакате да го(и) избришете обележаниот(те) писмо(а)?';
$messages['deletefolderconfirm']  = 'Дали сте сигурни дека сакате да ја избришете оваа папка?';
$messages['purgefolderconfirm']  = 'Дали сте сигурни дека сакате да ги избршете сите писма во оваа папка?';
$messages['contactdeleting'] = 'Контактот (контактите) се брише....';
$messages['folderdeleting'] = 'Ја бришам папката...';
$messages['foldermoving'] = 'Ја преместувам папката...';
$messages['formincomplete'] = 'Имате изоставено непополнети информации';
$messages['noemailwarning'] = 'Внесете валидна е-поштенска адреса';
$messages['nonamewarning']  = 'Внесете име';
$messages['nopagesizewarning'] = 'Внесете големина на страницата';
$messages['norecipientwarning'] = 'Внесете барем еден примач';
$messages['nosubjectwarning']  = 'Немате внесено „Наслов“. Дали сакате да внесете?';
$messages['nobodywarning'] = 'Писмото нема текст во него. Дали сакате да го испратите?';
$messages['notsentwarning'] = 'Писмото не е пратено. Дали сакате да го отфрлите?';
$messages['noldapserver'] = 'Изберете LDAP сервер за пребарување';
$messages['nosearchname'] = 'Внесете име или е-поштенска адреса';
$messages['notuploadedwarning'] = 'Сè уште нема подигнати прилози. Почекајте или откажете го подигањето';
$messages['searchsuccessful'] = 'Пронајадени се $nr пораки';
$messages['searchnomatch'] = 'Пребарувањето не даде резлутати';
$messages['searching'] = 'Пребарувам....';
$messages['checking'] = 'Проверувам...';
$messages['nospellerrors'] = 'Нема грешки во спелувањето';
$messages['folderdeleted'] = 'Папката е успешно избришана';
$messages['deletedsuccessfully'] = 'Успешно избришано';
$messages['converting'] = 'Форматирањето на писмото е отстрането...';
$messages['messageopenerror'] = 'Не можев да го вчитам писното од серверот';
$messages['fileuploaderror'] = 'Прикачувањето е неуспешно';
$messages['filesizeerror'] = 'Подигнатата податотека го надминува ограничувањето од $size';
$messages['sourceisreadonly'] = 'Изворот на оваа адреса неможе да се промени';
$messages['errorsavingcontact'] = 'Името неможе да се сними';
$messages['movingmessage'] = 'Пораката се преместува...';
$messages['receiptsent'] = 'Известувањето е успешно пратено';
$messages['errorsendingreceipt'] = 'Известувањето не е пратено';
$messages['nodeletelastidentity'] = 'Овој идентитет неможе да се избрише, тој е последниот.';
$messages['forbiddencharacter'] = 'Името на папката содржи несоодветен формат';
$messages['selectimportfile'] = 'Изберете ја податотеката која сакате да ја прикачите';
$messages['addresswriterror'] = 'Одбраниот именик не може да се менува';
$messages['importwait'] = 'Убезувам,, почекајте...';
$messages['importconfirm'] = '<b>Успешно се увезени $inserted имиња, $skipped веќе постојат и се прескокнати</b>:<p><em>$names</em></p>';
$messages['opnotpermitted'] = 'Операцијата не е дозволена';
$messages['httpreceivedencrypterror'] = 'Се појави фатална конфигурациска грешка. Веднаш контактирајте го администраторот. <b>Вашето писмо не мож.</b>';
$messages['smtpconnerror'] = 'SMTP грешка ($code): Не успеав да се поврзам со серверот';
$messages['smtpautherror'] = 'SMTP грешка: Не успееа потврдувањето';
$messages['smtpfromerror'] = 'SMTP грешка ($code): Не успеав да го поставам испраќачот „$from“ ($msg)';
$messages['smtptoerror'] = 'SMTP грешка ($code): Не успеав да го поставам примачот „$yo“ ($msg)';
$messages['smtprecipientserror'] = 'SMTP грешка: Не успеав да ја испарсирам листата на примачи';
$messages['smtperror'] = 'SMTP Error: $msg';
