<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/labels.inc                                        |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/labels/
*/
$labels['welcome']   = 'Wolkom by $product';
$labels['username']  = 'Brûkersnamme';
$labels['password']  = 'Wachtwurd';
$labels['server']    = 'Server';
$labels['login']     = 'Ynlogge';
$labels['logout']   = 'Ôfmelde';
$labels['mail']     = 'E-mail';
$labels['settings'] = 'Ynstellingen';
$labels['addressbook'] = 'Adresboek';
$labels['drafts'] = 'Konsepten';
$labels['sent']   = 'Stjoerd';
$labels['trash']  = 'Jiskefet';
$labels['junk']   = 'Spam';
$labels['subject'] = 'Ûnderwerp';
$labels['from']    = 'Fan';
$labels['to']      = 'Oan';
$labels['cc']      = 'Cc';
$labels['bcc']     = 'Bcc';
$labels['replyto'] = 'Antwurd oan';
$labels['followupto'] = 'Oanslutend oan';
$labels['date']    = 'Datum';
$labels['size']    = 'Grutte';
$labels['priority'] = 'Prioriteit';
$labels['organization'] = 'Organisaasje';
$labels['mailboxlist'] = 'Mappen';
$labels['messagenrof'] = 'Berjocht $nr fan $count';
$labels['copy']     = 'Kopieare';
$labels['move']     = 'Ferplaatse';
$labels['download'] = 'Delhelje';
$labels['showattachment'] = 'Toane';
$labels['filename'] = 'Triemnamme';
$labels['filesize'] = 'Triemgrutte';
$labels['sun'] = 'si';
$labels['mon'] = 'mo';
$labels['tue'] = 'ti';
$labels['wed'] = 'wo';
$labels['thu'] = 'to';
$labels['fri'] = 'fr';
$labels['sat'] = 'so';
$labels['sunday']    = 'snein';
$labels['monday']    = 'moandei';
$labels['tuesday']   = 'tiisdei';
$labels['wednesday'] = 'woansdei';
$labels['thursday']  = 'tongersdei';
$labels['friday']    = 'freed';
$labels['saturday']  = 'sneon';
$labels['jan']	= 'jan';
$labels['feb']	= 'feb';
$labels['mar']	= 'mrt';
$labels['apr']	= 'apr';
$labels['may']	= 'mai';
$labels['jun']	= 'jun';
$labels['jul'] 	= 'jul';
$labels['aug']	= 'aug';
$labels['sep']	= 'sep';
$labels['oct']	= 'okt';
$labels['nov']	= 'nov';
$labels['dec']	= 'des';
$labels['longjan']	= 'jannewaris';
$labels['longfeb']	= 'febrewaris';
$labels['longmar']	= 'maart';
$labels['longapr']	= 'april';
$labels['longmay']	= 'maaie';
$labels['longjun']	= 'juny';
$labels['longjul']	= 'july';
$labels['longaug']	= 'augustus';
$labels['longsep']	= 'septimber';
$labels['longoct']	= 'oktober';
$labels['longnov']	= 'novimber';
$labels['longdec']	= 'desimber';
$labels['today'] = 'Hjoed';
$labels['refresh']          = 'Ferfarskje';
$labels['reply']            = 'Beäntwurdzje';
$labels['more']             = 'Mear';
$labels['back']             = 'Werom';
$labels['options']          = 'Opsjes';
$labels['previous'] = 'Foarige';
$labels['next'] = 'Folgjende';
$labels['select'] = 'Selektearje';
$labels['all'] = 'Alle';
$labels['none'] = 'Gjin';
$labels['attachment'] = 'Taheakke';
$labels['nonesort'] = 'Gjin';
$labels['type'] = 'Type';
$labels['namex'] = 'Namme';
$labels['selectmedia']    = 'Fideo selektearje';
$labels['responsename'] = 'Namme';
$labels['andnmore']   = '$nr mear...';
$labels['htmltoggle'] = 'HTML';
$labels['country']      = 'Lân';
$labels['addcontact'] = 'Kontakt tafoegje';
$labels['editcontact'] = 'Kontakt bewurkje';
$labels['contacts'] = 'Kontakten';
$labels['edit']   = 'Bewurkje';
$labels['cancel'] = 'Annulearje';
$labels['delete'] = 'Fuortsmite';
$labels['addphoto'] = 'Tafoegje';
$labels['addgroup']       = 'Groep tafoegje';
$labels['groupdelete']    = 'Groep fuortsmite';
$labels['group'] = 'Groep';
$labels['done'] = 'Klear';
$labels['about'] = 'Oer';
$labels['preferences'] = 'Foarkarren';
$labels['htmlmessage'] = 'HTML-berjocht';
$labels['language']  = 'Taal';
$labels['timezone']  = 'Tiidsône';
$labels['newmessage'] = 'Nij berjocht';
$labels['folders'] = 'Mappen';
$labels['messagecount'] = 'Berjochten';
$labels['version'] = 'Ferzje';
$labels['source'] = 'Boarne';
$labels['license'] = 'Lisinsje';
$labels['B'] = 'B';
$labels['KB'] = 'KB';
$labels['MB'] = 'MB';
$labels['GB'] = 'GB';
$labels['unicode'] = 'Unicode';
$labels['english'] = 'Ingelsk';
$labels['greek'] = 'Gryksk';
$labels['turkish'] = 'Turksk';
$labels['japanese'] = 'Japansk';
$labels['korean'] = 'Koreaansk';
$labels['chinese'] = 'Sineesk';
?>
