<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/new_user_dialog/localization/<lang>.inc                       |
 |                                                                       |
 | Localization file of the Roundcube Webmail New User Dialog plugin     |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-new_user_dialog/
*/
$labels['identitydialogtitle'] = '請完成您的身份資訊';
$labels['identitydialoghint'] = '此視窗只會於第一次登入時出現。';
?>