<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Rhannu';
$labels['myrights'] = 'Hawliau Mynediad';
$labels['username'] = 'Defnyddiwr:';
$labels['advanced'] = 'Modd uwch';
$labels['newuser'] = 'Ychwanegu cofnod';
$labels['editperms'] = 'Golygu hawliau';
$labels['actions'] = 'Gweithredoedd hawl mynediad...';
$labels['anyone'] = 'Pob defnyddiwr (unrhywun)';
$labels['anonymous'] = 'Gwestai (anhysbys)';
$labels['identifier'] = 'Dynodwr';
$labels['acll'] = 'Chwilio';
$labels['aclr'] = 'Darllen negeseuon';
$labels['acls'] = 'Cadw stad Gwelwyd';
$labels['aclw'] = 'Fflagiau ysgrifennu';
$labels['acli'] = 'Mewnosod (Copïo fewn i)';
$labels['aclp'] = 'Postio';
$labels['aclc'] = 'Creu is-ffolderi';
$labels['aclk'] = 'Creu is-ffolderi';
$labels['acld'] = 'Dileu negeseuon';
$labels['aclt'] = 'Dileu negeseuon';
$labels['acle'] = 'Dileu';
$labels['aclx'] = 'Dileu ffolder';
$labels['acla'] = 'Gweinyddu';
$labels['acln'] = 'Anodi negeseuon';
$labels['aclfull'] = 'Rheolaeth lawn';
$labels['aclother'] = 'Arall';
$labels['aclread'] = 'Darllen';
$labels['aclwrite'] = 'Ysgrifennu';
$labels['acldelete'] = 'Dileu';
$labels['shortacll'] = 'Chwilio';
$labels['shortaclr'] = 'Darllen';
$labels['shortacls'] = 'Cadw';
$labels['shortaclw'] = 'Ysgrifennu';
$labels['shortacli'] = 'Mewnosod';
$labels['shortaclp'] = 'Postio';
$labels['shortaclc'] = 'Creu';
$labels['shortaclk'] = 'Creu';
$labels['shortacld'] = 'Dileu';
$labels['shortaclt'] = 'Dileu';
$labels['shortacle'] = 'Dileu';
$labels['shortaclx'] = 'Dileu ffolder';
$labels['shortacla'] = 'Gweinyddu';
$labels['shortacln'] = 'Anodi';
$labels['shortaclother'] = 'Arall';
$labels['shortaclread'] = 'Darllen';
$labels['shortaclwrite'] = 'Ysgrifennu';
$labels['shortacldelete'] = 'Dileu';
$labels['longacll'] = 'Mae\'r ffolder hwn i\'w weld ar y rhestrau a mae\'n bosib tanysgrifio iddo';
$labels['longaclr'] = 'Gellir agor y ffolder hwn i\'w ddarllen';
$labels['longacls'] = 'Gellir newid y fflag negeseuon Gwelwyd';
$labels['longaclw'] = 'Gellir newid y fflagiau negeseuon a allweddeiriau, heblaw Gwelwyd a Dilëuwyd';
$labels['longacli'] = 'Gellir ysgrifennu neu copïo negeseuon i\'r ffolder';
$labels['longaclp'] = 'Gellir postio negeseuon i\'r ffolder hwn';
$labels['longaclc'] = 'Gellir creu (neu ail-enwi) ffolderi yn uniongyrchol o dan y ffolder hwn';
$labels['longaclk'] = 'Gellir creu (neu ail-enwi) ffolderi yn uniongyrchol o dan y ffolder hwn';
$labels['longacld'] = 'Gellir newid fflag neges Dileu';
$labels['longaclt'] = 'Gellir newid fflag neges Dileu';
$labels['longacle'] = 'Gellir gwaredu negeseuon';
$labels['longaclx'] = 'Gellir dileu neu ail-enwi\'r ffolder';
$labels['longacla'] = 'Gellir newid hawliau mynediad y ffolder';
$labels['longacln'] = 'Gellir newid negeseuon metadata (anodiadau) a rannwyd';
$labels['longaclfull'] = 'Rheolaeth lawn yn cynnwys rheolaeth ffolderi';
$labels['longaclread'] = 'Gellir agor y ffolder hwn i\'w ddarllen';
$labels['longaclwrite'] = 'Gellir nodi, ysgrifennu neu copïo negeseuon i\'r ffolder';
$labels['longacldelete'] = 'Gellir dileu negeseuon';
$labels['longaclother'] = 'Hawliau mynediad eraill';
$labels['ariasummaryacltable'] = 'Rhestr o hawliau mynediad';
$labels['arialabelaclactions'] = 'Rhestru gweithrediadau';
$labels['arialabelaclform'] = 'Ffurflen hawliau mynediad';
$messages['deleting'] = 'Yn dileu hawliau mynediad...';
$messages['saving'] = 'Yn cadw hawliau mynediad...';
$messages['updatesuccess'] = 'Wedi newid hawliau mynediad yn llwyddiannus';
$messages['deletesuccess'] = 'Wedi dileu hawliau mynediad yn llwyddiannus';
$messages['createsuccess'] = 'Wedi ychwanegu hawliau mynediad yn llwyddiannus';
$messages['updateerror'] = 'Methwyd diweddaru hawliau mynediad';
$messages['deleteerror'] = 'Methwyd dileu hawliau mynediad';
$messages['createerror'] = 'Methwyd ychwanegu hawliau mynediad';
$messages['deleteconfirm'] = 'Ydych chi\'n siwr eich bod am ddileu hawliau mynediad y defnyddiwr/wyr ddewiswyd?';
$messages['norights'] = 'Nid oes hawliau wedi eu nodi!';
$messages['nouser'] = 'Nid oes enw defnyddiwr wedi ei nodi!';
?>
