<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Compartiendo';
$labels['myrights'] = 'Permisos de acceso';
$labels['username'] = 'Usuario:';
$labels['advanced'] = 'Modo avanzado';
$labels['newuser'] = 'Agregar entrada';
$labels['editperms'] = 'Editar permisos';
$labels['actions'] = 'Acciones para los permisos de acceso...';
$labels['anyone'] = 'Todos los usuarios (cualquiera)';
$labels['anonymous'] = 'Invitado (anonimo)';
$labels['identifier'] = 'Identificacion';
$labels['acll'] = 'Buscar';
$labels['aclr'] = 'Leer mensajes';
$labels['acls'] = 'Mantener como visualizado';
$labels['aclw'] = 'Escribir marcadores';
$labels['acli'] = 'Insertar (Copiar en)';
$labels['aclp'] = 'Publicar';
$labels['aclc'] = 'Crear subcarpetas';
$labels['aclk'] = 'Crear subcarpetas';
$labels['acld'] = 'Eliminar mensajes';
$labels['aclt'] = 'Eliminar mensajes';
$labels['acle'] = 'Descartar';
$labels['aclx'] = 'Eliminar carpeta';
$labels['acla'] = 'Administrar';
$labels['acln'] = 'Anotar mensajes';
$labels['aclfull'] = 'Control total';
$labels['aclother'] = 'Otro';
$labels['aclread'] = 'Leer';
$labels['aclwrite'] = 'Escribir';
$labels['acldelete'] = 'Eliminar';
$labels['shortacll'] = 'Buscar';
$labels['shortaclr'] = 'Leer';
$labels['shortacls'] = 'Mantener';
$labels['shortaclw'] = 'Escribir';
$labels['shortacli'] = 'Insertar';
$labels['shortaclp'] = 'Publicar';
$labels['shortaclc'] = 'Crear';
$labels['shortaclk'] = 'Crear';
$labels['shortacld'] = 'Eliminar';
$labels['shortaclt'] = 'Eliminar';
$labels['shortacle'] = 'Descartar';
$labels['shortaclx'] = 'Borrado de carpeta';
$labels['shortacla'] = 'Administrar';
$labels['shortacln'] = 'Anotar';
$labels['shortaclother'] = 'Otro';
$labels['shortaclread'] = 'Leer';
$labels['shortaclwrite'] = 'Escribir';
$labels['shortacldelete'] = 'Eliminar';
$labels['longacll'] = 'La carpeta es visible en listas y es posible suscribirse a ella';
$labels['longaclr'] = 'La carpeta se puede abirir para lectura';
$labels['longacls'] = 'El marcador de Mensajes Vistos puede ser modificado';
$labels['longaclw'] = 'Los marcadores de mensajes y palabras clave se pueden modificar, excepto Visto y Eliminado';
$labels['longacli'] = 'En esta carpeta se pueden escribir o copiar mensajes';
$labels['longaclp'] = 'En esta carpeta se pueden publicar mensajes';
$labels['longaclc'] = 'Debajo de esta carpeta se puede crear (o renombrar) otras carpetas directamente';
$labels['longaclk'] = 'Debajo de esta carpeta se puede crear (o renombrar) otras carpetas directamente';
$labels['longacld'] = 'El marcador de Mensaje Eliminado puede ser modificado';
$labels['longaclt'] = 'El marcador de Mensaje Eliminado puede ser modificado';
$labels['longacle'] = 'Los mensajes pueden ser descartados';
$labels['longaclx'] = 'La carpeta puede ser eliminada o renombrada';
$labels['longacla'] = 'Los permisos de acceso de esta carpeta pueden ser modificados';
$labels['longacln'] = 'La metainformación de mensajes compartidos (anotaciones) puede ser cambiada';
$labels['longaclfull'] = 'Control total incluyendo la administracion de carpeta';
$labels['longaclread'] = 'La carpeta se puede abrir para lectura';
$labels['longaclwrite'] = 'En esta carpeta los mensajes pueden ser marcados, escritos o copiados';
$labels['longacldelete'] = 'Los mensajes se pueden eliminar';
$labels['longaclother'] = 'Otros permisos de acceso';
$labels['ariasummaryacltable'] = 'Listado de permisos de acceso';
$labels['arialabelaclactions'] = 'Listar acciones';
$labels['arialabelaclform'] = 'Formulario de permisos de acceso';
$messages['deleting'] = 'Eliminando permisos de acceso...';
$messages['saving'] = 'Salvando permisos de acceso...';
$messages['updatesuccess'] = 'Permisos de acceso modificados satisfactoriamente';
$messages['deletesuccess'] = 'Permisos de acceso eliminados correctamente';
$messages['createsuccess'] = 'Permisos de acceso agregados satisfactoriamente';
$messages['updateerror'] = 'No se pudieron actualizar los permisos de acceso';
$messages['deleteerror'] = 'No se pueden eliminar los permisos de acceso';
$messages['createerror'] = 'No se pueden agregar los permisos de acceso';
$messages['deleteconfirm'] = 'Estas seguro que queres remover los permisos de acceso a el/los usuario(s) seleccionado/s?';
$messages['norights'] = 'Ningun permiso ha sido especificado!';
$messages['nouser'] = 'Ningun nombre de usuario ha sido especificado!';
?>
