<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Compartir';
$labels['myrights'] = 'Permisos de acceso';
$labels['username'] = 'Usuario:';
$labels['advanced'] = 'Modo avanzado';
$labels['newuser'] = 'Añadir una entrada';
$labels['editperms'] = 'Editar permisos';
$labels['actions'] = 'Acciones sobre los permisos de acceso…';
$labels['anyone'] = 'Todos los usuarios (cualquiera)';
$labels['anonymous'] = 'Invitados (anónimo)';
$labels['identifier'] = 'Identificador';
$labels['acll'] = 'Búsqueda';
$labels['aclr'] = 'Leer mensajes';
$labels['acls'] = 'Mantener como "Leído';
$labels['aclw'] = 'Escribir etiquetas';
$labels['acli'] = 'Insertar (Copiar dentro)';
$labels['aclp'] = 'Enviar';
$labels['aclc'] = 'Crear subcarpetas';
$labels['aclk'] = 'Crear subcarpetas';
$labels['acld'] = 'Borrar mensajes';
$labels['aclt'] = 'Borrar mensajes';
$labels['acle'] = 'Expurgar';
$labels['aclx'] = 'Borrar carpeta';
$labels['acla'] = 'Administrar';
$labels['acln'] = 'Anotar mensajes';
$labels['aclfull'] = 'Control total';
$labels['aclother'] = 'Otro';
$labels['aclread'] = 'Leer';
$labels['aclwrite'] = 'Escribir';
$labels['acldelete'] = 'Borrar';
$labels['shortacll'] = 'Búsqueda';
$labels['shortaclr'] = 'Leer';
$labels['shortacls'] = 'Conservar';
$labels['shortaclw'] = 'Escribir';
$labels['shortacli'] = 'Insertar';
$labels['shortaclp'] = 'Enviar';
$labels['shortaclc'] = 'Crear';
$labels['shortaclk'] = 'Crear';
$labels['shortacld'] = 'Borrar';
$labels['shortaclt'] = 'Borrar';
$labels['shortacle'] = 'Expurgar';
$labels['shortaclx'] = 'Borrar carpeta';
$labels['shortacla'] = 'Administrar';
$labels['shortacln'] = 'Anotar';
$labels['shortaclother'] = 'Otro';
$labels['shortaclread'] = 'Leer';
$labels['shortaclwrite'] = 'Escribir';
$labels['shortacldelete'] = 'Borrar';
$labels['longacll'] = 'La carpeta es visible en las listas y es posible suscribirse a ella';
$labels['longaclr'] = 'Se puede abrir la carpeta para leer';
$labels['longacls'] = 'Se pueden cambiar los mensajes con la etiqueta "Leído';
$labels['longaclw'] = 'Las etiquetas de mensaje y las palabras clave se pueden cambiar, excepto "Leído" y "Borrado';
$labels['longacli'] = 'Se pueden escribir mensajes o copiarlos a la carpeta';
$labels['longaclp'] = 'Se pueden enviar mensajes a esta carpeta';
$labels['longaclc'] = 'Se pueden crear (o renombrar) carpetas directamente bajo esta carpeta';
$labels['longaclk'] = 'Se pueden crear (o renombrar) carpetas directamente bajo esta carpeta';
$labels['longacld'] = 'No se pueden cambiar los mensajes etiquetados como "Borrado';
$labels['longaclt'] = 'No se pueden cambiar los mensajes etiquetados como "Borrado';
$labels['longacle'] = 'No se pueden expurgar los mensajes';
$labels['longaclx'] = 'La carpeta se puede borrar o renombrar';
$labels['longacla'] = 'Se pueden cambiar los permisos de acceso';
$labels['longacln'] = 'Los metadatos compartidos de los mensajes (anotaciones) pueden cambiarse';
$labels['longaclfull'] = 'Control total, incluyendo la gestión de carpetas';
$labels['longaclread'] = 'Se puede abrir la carpeta para leer';
$labels['longaclwrite'] = 'Se pueden etiquetar, escribir o copiar mensajes a la carpeta';
$labels['longacldelete'] = 'Los mensajes se pueden borrar';
$labels['longaclother'] = 'Otros derechos de acceso';
$labels['ariasummaryacltable'] = 'Lista de derechos de acceso';
$labels['arialabelaclactions'] = 'Lista de acciones';
$labels['arialabelaclform'] = 'Formulario de derechos de acceso';
$messages['deleting'] = 'Borrando permisos de acceso…';
$messages['saving'] = 'Guardando permisos de acceso…';
$messages['updatesuccess'] = 'Se han cambiado los permisos de acceso';
$messages['deletesuccess'] = 'Se han borrado los permisos de acceso';
$messages['createsuccess'] = 'Se han añadido los permisos de acceso';
$messages['updateerror'] = 'No ha sido posible actualizar los derechos de acceso';
$messages['deleteerror'] = 'No se han podido borrar los permisos de acceso';
$messages['createerror'] = 'No se han podido añadir los permisos de acceso';
$messages['deleteconfirm'] = '¿Seguro que quiere borrar los permisos de acceso del usuairo seleccionado?';
$messages['norights'] = 'No se han especificado los permisos de acceso';
$messages['nouser'] = 'No se ha especificado un nombre de usuario';
?>
