<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Compartindo';
$labels['myrights'] = 'Permisos de acceso';
$labels['username'] = 'Utente:';
$labels['advanced'] = 'Modo avanzado';
$labels['newuser'] = 'Engadir entrada';
$labels['editperms'] = 'Editar permisos';
$labels['actions'] = 'Accións sobre os Permisos de acceso...';
$labels['anyone'] = 'Todas as persoas usuarias (calquera)';
$labels['anonymous'] = 'Persoas convidadas (anónimo)';
$labels['identifier'] = 'Identificador';
$labels['acll'] = 'Bloquear';
$labels['aclr'] = 'Ler mensaxes';
$labels['acls'] = 'Manter estado actividade';
$labels['aclw'] = 'Marcas de lectura';
$labels['acli'] = 'Engadir (Copiar en)';
$labels['aclp'] = 'Envío';
$labels['aclc'] = 'Crear subcartafoles';
$labels['aclk'] = 'Crear subcartafoles';
$labels['acld'] = 'Borrar mensaxes';
$labels['aclt'] = 'Borrar mensaxes';
$labels['acle'] = 'Expurga';
$labels['aclx'] = 'Eliminar cartafol';
$labels['acla'] = 'Administrar';
$labels['acln'] = 'Crear anotacións para as mensaxes';
$labels['aclfull'] = 'Control total';
$labels['aclother'] = 'Outros';
$labels['aclread'] = 'Lectura';
$labels['aclwrite'] = 'Escritura';
$labels['acldelete'] = 'Borrado';
$labels['shortacll'] = 'Buscar';
$labels['shortaclr'] = 'Ler';
$labels['shortacls'] = 'Manter';
$labels['shortaclw'] = 'Escribir';
$labels['shortacli'] = 'Inserir';
$labels['shortaclp'] = 'Publicar';
$labels['shortaclc'] = 'Crear';
$labels['shortaclk'] = 'Crear';
$labels['shortacld'] = 'Eliminar';
$labels['shortaclt'] = 'Eliminar';
$labels['shortacle'] = 'Expurga';
$labels['shortaclx'] = 'Eliminar cartafol';
$labels['shortacla'] = 'Administrar';
$labels['shortacln'] = 'Crear anotación';
$labels['shortaclother'] = 'Outros';
$labels['shortaclread'] = 'Lectura';
$labels['shortaclwrite'] = 'Escritura';
$labels['shortacldelete'] = 'Eliminar';
$labels['longacll'] = 'O cartafol é visíbel e pode ser subscrito';
$labels['longaclr'] = 'Pódese abrir o cartafol para lectura';
$labels['longacls'] = 'Pódese mudar o marcador de Mensaxes Enviadas';
$labels['longaclw'] = 'Pódense mudar marcadores e palabras chave agás Vistas e Borradas';
$labels['longacli'] = 'Pódense escreber ou copiar as mensaxes a este cartafol';
$labels['longaclp'] = 'Pódense enviar as mensaxes a este cartafol';
$labels['longaclc'] = 'Pódense crear (ou renomear) os cartafoles directamente baixo deste cartafol';
$labels['longaclk'] = 'Pódense crear (ou renomear) os cartafoles directamente baixo deste cartafol';
$labels['longacld'] = 'Pódense mudar as mensaxes coa marca Eliminar';
$labels['longaclt'] = 'Pódense mudar as mensaxes coa marca Eliminar';
$labels['longacle'] = 'As mensaxes poden ser expurgadas';
$labels['longaclx'] = 'Pódese borrar ou renomear o cartafol';
$labels['longacla'] = 'Pódense mudar os permisos de acceso ao cartafol';
$labels['longacln'] = 'Pódense trocar as anotacións das mensaxes';
$labels['longaclfull'] = 'Control total inclúe administración de cartafoles';
$labels['longaclread'] = 'Pódese abrir o cartafol para lectura';
$labels['longaclwrite'] = 'Pódense marcar, escribir ou copiar as mensaxes no cartafol';
$labels['longacldelete'] = 'Pódense borrar as mensaxes';
$labels['longaclother'] = 'Outros dereitos de acceso';
$labels['ariasummaryacltable'] = 'Lista de dereitos de acceso';
$labels['arialabelaclactions'] = 'Accións de lista';
$labels['arialabelaclform'] = 'Formulario de dereitos de acceso';
$messages['deleting'] = 'Borrando permisos de acceso...';
$messages['saving'] = 'Gardando permisos de acceso...';
$messages['updatesuccess'] = 'Mudados con éxito os permisos de acceso';
$messages['deletesuccess'] = 'Borrados con éxito os permisos de acceso';
$messages['createsuccess'] = 'Engadidos con éxito os permisos de acceso';
$messages['updateerror'] = 'Non se poden actualizar os permisos de acceso';
$messages['deleteerror'] = 'Non se poden borrar os permisos de acceso';
$messages['createerror'] = 'Non se poden engadir permisos de acceso';
$messages['deleteconfirm'] = 'De certo que queres eliminar os permisos de acceso da(s) persoa(s) usuaria(s) escollida(s)?';
$messages['norights'] = 'Non se especificaron permisos!';
$messages['nouser'] = 'Non se especificou o nome da persoa usuaria!';
?>
