<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Deling';
$labels['myrights'] = 'Tilgangsrettar';
$labels['username'] = 'Brukar:';
$labels['newuser'] = 'Legg til oppføring';
$labels['actions'] = 'Val for tilgangsrettar...';
$labels['anyone'] = 'Alle brukarar (alle)';
$labels['anonymous'] = 'Gjester (anonyme)';
$labels['identifier'] = 'Identifikator';
$labels['acll'] = 'Oppslag';
$labels['aclr'] = 'Les meldingar';
$labels['acls'] = 'Behald lesestatus';
$labels['aclw'] = 'Skriveflagg';
$labels['acli'] = 'Lim inn';
$labels['aclp'] = 'Post';
$labels['aclc'] = 'Opprett undermapper';
$labels['aclk'] = 'Opprett undermapper';
$labels['acld'] = 'Slett meldingar';
$labels['aclt'] = 'Slett meldingar';
$labels['acle'] = 'Slett fullstendig';
$labels['aclx'] = 'Slett mappe';
$labels['acla'] = 'Administrér';
$labels['aclfull'] = 'Full kontroll';
$labels['aclother'] = 'Anna';
$labels['aclread'] = 'Les';
$labels['aclwrite'] = 'Skriv';
$labels['acldelete'] = 'Slett';
$labels['shortacll'] = 'Oppslag';
$labels['shortaclr'] = 'Les';
$labels['shortacls'] = 'Behald';
$labels['shortaclw'] = 'Skriv';
$labels['shortacli'] = 'Sett inn';
$labels['shortaclp'] = 'Post';
$labels['shortaclc'] = 'Opprett';
$labels['shortaclk'] = 'Opprett';
$labels['shortacld'] = 'Slett';
$labels['shortaclt'] = 'Slett';
$labels['shortacle'] = 'Slett fullstendig';
$labels['shortaclx'] = 'Slett mappe';
$labels['shortacla'] = 'Administrér';
$labels['shortaclother'] = 'Anna';
$labels['shortaclread'] = 'Les';
$labels['shortaclwrite'] = 'Skriv';
$labels['shortacldelete'] = 'Slett';
$labels['longacll'] = 'Mappa er synleg og kan abonnerast på';
$labels['longaclr'] = 'Mappa kan opnast for lesing';
$labels['longacls'] = 'Meldingane sine lesestatusflagg kan endrast';
$labels['longaclw'] = 'Meldingsflagg og -nøkkelord kan endrast, bortsett frå status for lesing og sletting';
$labels['longacli'] = 'Meldingar kan lagrast eller kopierast til mappa';
$labels['longaclp'] = 'Meldingar kan postast til denne mappa';
$labels['longaclc'] = 'Mapper kan opprettast (eller namnast om) direkte under denne mappa';
$labels['longaclk'] = 'Mapper kan opprettast (eller namnast om) direkte under denne mappa';
$labels['longacld'] = 'Meldingane sine flagg for sletting kan endrast';
$labels['longaclt'] = 'Meldingane sine flagg for sletting kan endrast';
$labels['longacle'] = 'Meldinga kan slettast for godt';
$labels['longaclx'] = 'Mappa kan slettast eller få nytt namn';
$labels['longacla'] = 'Mappa sine tilgangsrettar kan endrast';
$labels['longaclfull'] = 'Full kontroll, inkludert mappeadministrasjon';
$labels['longaclread'] = 'Mappa kan opnast for lesing';
$labels['longaclwrite'] = 'Meldingar kan merkast, lagrast i eller flyttast til mappa';
$labels['longacldelete'] = 'Meldinga kan slettast';
$messages['deleting'] = 'Slettar tilgangsrettar…';
$messages['saving'] = 'Lagrar tilgangsrettar…';
$messages['updatesuccess'] = 'Tilgangsrettiar vart endra';
$messages['deletesuccess'] = 'Tilgangsretter vart sletta';
$messages['createsuccess'] = 'Tilgangsrettar vart legne til';
$messages['deleteerror'] = 'Kunne ikkje fjerne tilgangsrettar';
$messages['createerror'] = 'Kunne ikkje leggje til tilgangsrettar';
$messages['deleteconfirm'] = 'Er du sikker på at du vil fjerne tilgangen til  valde brukarar?';
$messages['norights'] = 'Ingen rettar er spesifisert!';
$messages['nouser'] = 'Brukarnamn er ikkje spesifisert!';
?>
