<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['username'] = 'Uçeir:';
$labels['anonymous'] = 'Gästs (anonimös)';
$labels['acldelete'] = 'Zeletarh';
$labels['shortacld'] = 'Zeletarh';
$labels['shortaclt'] = 'Zeletarh';
$labels['shortacldelete'] = 'Zeletarh';
?>
