<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = 'Поширення';
$labels['myrights'] = 'Права доступу';
$labels['username'] = 'Користувач:';
$labels['advanced'] = 'Розширений режим';
$labels['newuser'] = 'Додати запис';
$labels['editperms'] = 'Редагувати дозволи';
$labels['actions'] = 'Дії з правами доступу…';
$labels['anyone'] = 'Усі користувачі (будь-хто)';
$labels['anonymous'] = 'Гості (аноніми)';
$labels['identifier'] = 'Ідентифікатор';
$labels['acll'] = 'Пошук';
$labels['aclr'] = 'Прочитані повідомлення';
$labels['acls'] = 'Зберегти статус «Прочитано»';
$labels['aclw'] = 'Прапорці написання';
$labels['acli'] = 'Вставити (Копіювати в)';
$labels['aclp'] = 'Допис';
$labels['aclc'] = 'Створити підтеки';
$labels['aclk'] = 'Створити підтеки';
$labels['acld'] = 'Вилучити повідомлення';
$labels['aclt'] = 'Вилучити повідомлення';
$labels['acle'] = 'Викреслити';
$labels['aclx'] = 'Вилучити теку';
$labels['acla'] = 'Адмініструвати';
$labels['acln'] = 'Анотувати повідомлення';
$labels['aclfull'] = 'Повний контроль';
$labels['aclother'] = 'Інше';
$labels['aclread'] = 'Читати';
$labels['aclwrite'] = 'Писати';
$labels['acldelete'] = 'Вилучити';
$labels['shortacll'] = 'Пошук';
$labels['shortaclr'] = 'Читати';
$labels['shortacls'] = 'Залишити';
$labels['shortaclw'] = 'Писати';
$labels['shortacli'] = 'Вставити';
$labels['shortaclp'] = 'Дописати';
$labels['shortaclc'] = 'Створити';
$labels['shortaclk'] = 'Створити';
$labels['shortacld'] = 'Вилучити';
$labels['shortaclt'] = 'Вилучити';
$labels['shortacle'] = 'Викреслити';
$labels['shortaclx'] = 'Вилучити теку';
$labels['shortacla'] = 'Адмініструвати';
$labels['shortacln'] = 'Анотувати';
$labels['shortaclother'] = 'Інше';
$labels['shortaclread'] = 'Читати';
$labels['shortaclwrite'] = 'Писати';
$labels['shortacldelete'] = 'Вилучити';
$labels['longacll'] = 'Тека видима у списках і на неї можна підписатись';
$labels['longaclr'] = 'Теку можна відкрити для читання';
$labels['longacls'] = 'Прапорець «Прочитано» на повідомленнях можна змінити';
$labels['longaclw'] = 'Прапорці і ключові слова повідомлень можна змінити, окрім «Прочитано» і «Вилучено»';
$labels['longacli'] = 'Повідомлення можна записати або копіювати у теку';
$labels['longaclp'] = 'Повідомлення можна публікувати в цю теку';
$labels['longaclc'] = 'Теки можна створювати (чи перейменовувати) прямо під цією текою';
$labels['longaclk'] = 'Теки можна створювати (чи перейменовувати) прямо під цією текою';
$labels['longacld'] = 'Прапорець «Вилучено» на повідомленнях можна змінити';
$labels['longaclt'] = 'Прапорець «Вилучено» на повідомленнях можна змінити';
$labels['longacle'] = 'Повідомлення можна викреслити';
$labels['longaclx'] = 'Теку можна вилучити чи перейменувати';
$labels['longacla'] = 'Права доступу до теки можна змінити';
$labels['longacln'] = 'Поширені метадані (анотації) повідомлень можна змінити';
$labels['longaclfull'] = 'Повний контроль, включно з адмініструванням тек';
$labels['longaclread'] = 'Теку можна відкрити для читання';
$labels['longaclwrite'] = 'Повідомлення можна позначити, записати або копіювати у теку';
$labels['longacldelete'] = 'Повідомлення можна вилучити';
$labels['longaclother'] = 'Інші права доступу';
$labels['ariasummaryacltable'] = 'Список прав доступу';
$labels['arialabelaclactions'] = 'Перелічити дії';
$labels['arialabelaclform'] = 'Форма прав доступу';
$messages['deleting'] = 'Вилучення прав доступу…';
$messages['saving'] = 'Збереження прав доступу…';
$messages['updatesuccess'] = 'Права доступу успішно змінені';
$messages['deletesuccess'] = 'Права доступу успішно вилучені';
$messages['createsuccess'] = 'Права доступу успішно додані';
$messages['updateerror'] = 'Не вдалося оновити права доступу';
$messages['deleteerror'] = 'Не вдалося вилучити права доступу';
$messages['createerror'] = 'Не вдалося додати права доступу';
$messages['deleteconfirm'] = 'Ви дійсно хочете вилучити права доступу обраного користувача(-ів)?';
$messages['norights'] = 'Жодних прав не вказано!';
$messages['nouser'] = 'Жодного імені користувача не вказано!';
?>
