<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/acl/localization/<lang>.inc                                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail ACL plugin                 |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-acl/
*/
$labels['sharing'] = '分享';
$labels['myrights'] = '存取權限';
$labels['username'] = '使用者：';
$labels['newuser'] = '新增項目';
$labels['actions'] = '權限設定';
$labels['anyone'] = '所有使用者 (anyone)';
$labels['anonymous'] = '訪客 (anonymous)';
$labels['identifier'] = '識別';
$labels['acll'] = '尋找';
$labels['aclr'] = '讀取訊息';
$labels['acls'] = '保持上線狀態';
$labels['aclw'] = '寫入標幟';
$labels['acli'] = '插入(複製到這裡)';
$labels['aclp'] = '發表';
$labels['aclc'] = '建立子資料夾';
$labels['aclk'] = '建立子資料夾';
$labels['acld'] = '刪除訊息';
$labels['aclt'] = '刪除訊息';
$labels['acle'] = '刪去';
$labels['aclx'] = '刪除資料夾';
$labels['acla'] = '管理者';
$labels['aclfull'] = '完全控制';
$labels['aclother'] = '其它';
$labels['aclread'] = '讀取';
$labels['aclwrite'] = '寫入';
$labels['acldelete'] = '刪除';
$labels['shortacll'] = '尋找';
$labels['shortaclr'] = '讀取';
$labels['shortacls'] = '保存';
$labels['shortaclw'] = '寫入';
$labels['shortacli'] = '插入';
$labels['shortaclp'] = '發表';
$labels['shortaclc'] = '建立';
$labels['shortaclk'] = '建立';
$labels['shortacld'] = '刪除';
$labels['shortaclt'] = '刪除';
$labels['shortacle'] = '刪去';
$labels['shortaclx'] = '資料夾刪除';
$labels['shortacla'] = '管理者';
$labels['shortaclother'] = '其它';
$labels['shortaclread'] = '讀取';
$labels['shortaclwrite'] = '寫入';
$labels['shortacldelete'] = '刪除';
$labels['longacll'] = '此資料夾權限可以訂閱和瀏覽';
$labels['longaclr'] = '資料夾能被打開與讀取';
$labels['longacls'] = '能修改訊息標幟';
$labels['longaclw'] = '內容旗標和關鍵字可以變更,不包含已檢視和刪除的';
$labels['longacli'] = '訊息能寫入或複製到資料夾';
$labels['longaclp'] = '訊息能被投遞到這個資料夾';
$labels['longaclc'] = '這個資料夾之下可以建子資料夾(或重新命名）';
$labels['longaclk'] = '這個資料夾之下可以建子資料夾(或重新命名）';
$labels['longacld'] = '能修改訊息刪除標幟';
$labels['longaclt'] = '能修改訊息刪除標幟';
$labels['longacle'] = '能抹除訊息';
$labels['longaclx'] = '資料夾能被刪除或重新命名';
$labels['longacla'] = '能變更資料夾權限';
$labels['longaclfull'] = '完全控制包含資料夾管理';
$labels['longaclread'] = '資料夾能被打開與讀取';
$labels['longaclwrite'] = '信件可以被標記、編寫或複製到資料夾';
$labels['longacldelete'] = '訊息能被刪除';
$messages['deleting'] = '刪除權限...';
$messages['saving'] = '儲存權限...';
$messages['updatesuccess'] = '權限變更完成';
$messages['deletesuccess'] = '權限刪除完成';
$messages['createsuccess'] = '權限新增完成';
$messages['updateerror'] = '無法更新權限';
$messages['deleteerror'] = '無法刪除權限';
$messages['createerror'] = '無法新增權限';
$messages['deleteconfirm'] = '您確定要刪除所選取使用者的權限嗎?';
$messages['norights'] = '沒有指定任何權限';
$messages['nouser'] = '沒有指定用戶名稱';
?>
