<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['messagedelete'] = 'Berjocht fuortsmite';
$labels['del'] = 'Fuortsmite';
$labels['none'] = 'gjin';
$labels['notifyimportance'] = 'Prioriteit:';
$labels['notifymethodmailto'] = 'E-mail';
$labels['notifymethodsms'] = 'SMS';
$labels['...'] = '...';
$labels['datetest'] = 'Date';
$labels['year'] = 'jier';
$labels['month'] = 'moanne';
$labels['day'] = 'dei';
$labels['hour'] = 'oerre';
$labels['minute'] = 'minút';
$labels['second'] = 'sekonde';
$labels['time'] = 'tiid (oo:mm:ss)';
$labels['iso8601'] = 'datum (ISO8601)';
$labels['std11'] = 'datum (RFC2822)';
$labels['zone'] = 'tiidsône';
$labels['text'] = 'tekst';
$labels['modtype'] = 'type:';
$labels['domain'] = 'domein';
$labels['user'] = 'brûker';
$labels['vacation.status'] = 'Status';
?>
