<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filterany'] = 'hemû peyam';
$labels['filtercontains'] = 'dihewîne';
$labels['filternotcontains'] = 'nahebîne';
$labels['filteris'] = 'weke';
$labels['filterisnot'] = 'ne weke';
$labels['filterexists'] = 'heye';
$labels['filternotexists'] = 'tune ye';
$labels['filterunder'] = 'bin';
$labels['filterover'] = 'ser';
$labels['messagemoveto'] = 'Peyamê bibe ';
$labels['messageredirect'] = 'Peyamê vegerîne';
$labels['messagereply'] = 'Bi peyamekê bibersivîne';
$labels['messagedelete'] = 'Peyamê jê bibe';
$labels['add'] = 'Tev bike';
$labels['del'] = 'Jê bibe';
$labels['sender'] = 'Şandyar';
$labels['vacationsubject'] = 'Mijara peyamê:';
$labels['days'] = 'roj';
$labels['seconds'] = 'saniye';
$labels['enable'] = 'Veke/Bigire';
$labels['active'] = 'çalak';
$labels['none'] = 'qet';
$labels['fromfile'] = 'ji dosyeyê';
$labels['filterdisabled'] = 'Parzing girtî ye';
$labels['countisgreaterthan'] = 'hejmar mezintir e ji';
$labels['countisgreaterthanequal'] = 'hejmar weke an jî mezintir e ji';
$labels['countislessthan'] = 'hejmar kêmtir e ji';
$labels['countequals'] = 'hejmar weke ';
$labels['countnotequals'] = 'hejmar ne weke';
$labels['flagread'] = 'Xwendî';
$labels['flagdeleted'] = 'Jêbirî';
$labels['flaganswered'] = 'Nebersivandî';
$labels['flagflagged'] = 'Bialakirî';
$labels['varlength'] = 'Dirêjahî';
$labels['notify'] = 'Agahiyê bişîne';
$labels['notifyimportance'] = 'Girîng:';
$labels['notifyimportancelow'] = 'nizm';
$labels['notifyimportancehigh'] = 'bilind';
$labels['notifymethodmailto'] = 'Email';
$labels['notifymethodtel'] = 'Telefon';
$labels['notifymethodsms'] = 'SMS';
$labels['filtercreate'] = 'Parzingek çêke';
$labels['nextstep'] = 'Gava pêşde';
$labels['...'] = '...';
$labels['currdate'] = 'Dîroka niha';
$labels['datetest'] = 'Dîrok';
$labels['year'] = 'sal';
$labels['month'] = 'meh';
$labels['day'] = 'roj';
$labels['date'] = 'dîrok (ssss-mm--rr)';
$labels['julian'] = 'dîrok (julian)';
$labels['hour'] = 'saet';
$labels['minute'] = 'deqîqe';
$labels['second'] = 'saniye';
$labels['time'] = 'dem (ss:dd:ss)';
$labels['iso8601'] = 'dem (ISO8601)';
$labels['zone'] = 'qada demê';
$labels['weekday'] = 'rojên hefteyê (0-6)';
$labels['address'] = 'navnîşan';
$labels['text'] = 'nivîs';
$labels['contenttype'] = 'cûreya naverokê';
$labels['modtype'] = 'cûre';
$labels['allparts'] = 'hemû';
$labels['user'] = 'bikarhêner';
$labels['detail'] = 'detay';
$labels['vacation.reply'] = 'Peyamê bibersivîne';
$labels['vacation.advanced'] = 'Mihengên pêşketî';
$labels['vacation.subject'] = 'Mijar';
$labels['vacation.status'] = 'Rewş';
$labels['vacation.on'] = 'Vekirî';
?>
