<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filters'] = 'පෙරහණ';
$labels['moveup'] = 'ඉහළට ගෙනයන්න';
$labels['movedown'] = 'පහළට ගෙනයන්න';
$labels['filterany'] = 'සියලු පණිවිඩ';
$labels['filtercontains'] = 'අඩංගු';
$labels['messagedelete'] = 'පණිවිඩය මකන්න';
$labels['add'] = 'එක් කරන්න';
$labels['del'] = 'මකන්න';
$labels['sender'] = 'යවන්නා';
$labels['recipient'] = 'ලබන්නා';
$labels['vacationsubject'] = 'පණිවිඩයේ මාතෘකාව:';
$labels['enable'] = 'සක්‍රීය කරන්න/අක්‍රීය කරන්න';
$labels['active'] = 'සක්‍රීය';
$labels['none'] = 'කිසිවක් නැත';
$labels['flagread'] = 'කියවන්න';
$labels['flagdeleted'] = 'මකන ලදී';
$labels['flagdraft'] = 'කටු සටහන';
$labels['nextstep'] = 'මීලග පියවර';
$labels['...'] = '...';
$labels['address'] = 'ලිපිනය';
$labels['envelope'] = 'ලියුම් කවරය';
$labels['modtype'] = 'වර්ගය:';
$labels['allparts'] = 'සියල්ල';
$messages['nametoolong'] = 'නම දිග වැඩිය.';
?>
