<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filters'] = 'Филтери';
$labels['managefilters'] = 'Управљај филтерима долазне поште';
$labels['filtername'] = 'Назив филтера';
$labels['newfilter'] = 'Нови филтер';
$labels['filteradd'] = 'Додај филтер';
$labels['filterdel'] = 'Обриши филтер';
$labels['moveup'] = 'Помери горе';
$labels['movedown'] = 'Помери доле';
$labels['filterallof'] = 'поклопи сва ова правила';
$labels['filteranyof'] = 'поклопи било које од ових правила';
$labels['filterany'] = 'све поруке';
$labels['filtercontains'] = 'садржи';
$labels['filternotcontains'] = 'не садржи';
$labels['filteris'] = 'је једнак';
$labels['filterisnot'] = 'није једнак';
$labels['filterexists'] = 'постоји';
$labels['filternotexists'] = 'не постоји';
$labels['filtermatches'] = 'поклапа израз';
$labels['filternotmatches'] = 'не поклапа израз';
$labels['filterregex'] = 'поклапа регуларни израз';
$labels['filternotregex'] = 'не поклапа регуларни израз';
$labels['filterunder'] = 'испод';
$labels['filterover'] = 'преко';
$labels['addrule'] = 'Додај правило';
$labels['delrule'] = 'Обриши правило';
$labels['messagemoveto'] = 'Премести поруку у';
$labels['messageredirect'] = 'Преусмери поруку у';
$labels['messagecopyto'] = 'Копирај поруку у';
$labels['messagesendcopy'] = 'Пошаљи копију поруке за';
$labels['messagereply'] = 'Одговори поруком';
$labels['messagedelete'] = 'Обриши поруку';
$labels['messagediscard'] = 'Одбаци поруком';
$labels['messagekeep'] = 'Задржи поруку у примљеним';
$labels['messagesrules'] = 'За долазну пошту:';
$messages['filterunknownerror'] = 'Непозната грешка сервера.';
$messages['filterconnerror'] = 'Не могу да се повежем на сервер.';
?>
