<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filters'] = 'ตัวกรองข้อมูล';
$labels['filtername'] = 'ชื่อตัวกรองข้อมูล';
$labels['newfilter'] = 'สร้างตัวกรองข้อมูลใหม่';
$labels['filteradd'] = 'เพิ่มตัวกรองข้อมูล';
$labels['filterdel'] = 'ลบตัวกรองข้อมูล';
$labels['moveup'] = 'เลื่อนขึ้น';
$labels['movedown'] = 'เลื่อนลง';
$labels['filterany'] = 'ข้อความทั้งหมด';
$labels['filtercontains'] = 'ที่มีคำว่า';
$labels['filternotcontains'] = 'ไม่มีคำว่า';
$labels['filteris'] = 'ที่มีค่าเท่ากับ';
$labels['filterisnot'] = 'ที่มีค่าไม่เท่ากับ';
$labels['addrule'] = 'เพิ่มกฏ';
$labels['delrule'] = 'ลบกฏ';
$labels['messagemoveto'] = 'ย้ายข้อความไปที่';
$labels['messageredirect'] = 'เปลียนเส้นทางข้อความไปที่';
$labels['messagecopyto'] = 'คัดลอกข้อความไปที่';
$labels['messagesendcopy'] = 'ส่งข้อความคัดลอกไปที่';
$labels['messagedelete'] = 'ลบข้อความ';
$labels['messagediscard'] = 'ยกเลิกข้อความ';
$labels['messagesrules'] = 'สำหรับอีเมลขาเข้า:';
$labels['add'] = 'เพิ่ม';
$labels['del'] = 'ลบ';
$labels['sender'] = 'ผู้ส่ง';
$labels['recipient'] = 'ผู้รับ';
$labels['vacationsubject'] = 'หัวเรื่องข้อความ:';
$labels['enable'] = 'เปิดใช้งาน/ปิดใช้งาน';
?>
