<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/managesieve/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Managesieve plugin         |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-managesieve/
*/
$labels['filters'] = '篩選器';
$labels['managefilters'] = '設定篩選器';
$labels['filtername'] = '篩選器名稱';
$labels['newfilter'] = '建立新篩選器';
$labels['filteradd'] = '增加篩選器';
$labels['filterdel'] = '刪除篩選器';
$labels['moveup'] = '上移';
$labels['movedown'] = '下移';
$labels['filterallof'] = '符合所有規則';
$labels['filteranyof'] = '符合任一條規則';
$labels['filterany'] = '所有信件';
$labels['filtercontains'] = '包含';
$labels['filternotcontains'] = '不包含';
$labels['filteris'] = '等於';
$labels['filterisnot'] = '不等於';
$labels['filterexists'] = '存在';
$labels['filternotexists'] = '不存在';
$labels['filtermatches'] = '符合表達式';
$labels['filternotmatches'] = '不符合表達式';
$labels['filterregex'] = '符合正規表達式';
$labels['filternotregex'] = '不符合正規表達式';
$labels['filterunder'] = '小於';
$labels['filterover'] = '大於';
$labels['addrule'] = '新增規則';
$labels['delrule'] = '刪除規則';
$labels['messagemoveto'] = '將信件移至';
$labels['messageredirect'] = '將信件轉寄至';
$labels['messagecopyto'] = '複製訊息至';
$labels['messagesendcopy'] = '寄送訊息複本至';
$labels['messagereply'] = '以下列內容回覆';
$labels['messagedelete'] = '刪除信件';
$labels['messagediscard'] = '刪除信件並以下列內容回覆';
$labels['messagekeep'] = '在收件匣保留郵件';
$labels['messagesrules'] = '對新收到的信件：';
$labels['messagesactions'] = '執行下列動作：';
$labels['add'] = '新增';
$labels['del'] = '刪除';
$labels['sender'] = '寄件者';
$labels['recipient'] = '收件者';
$labels['vacationdays'] = '多久回覆一次（單位：天）：';
$labels['vacationreason'] = '信件內容（休假原因）：';
$labels['vacationsubject'] = '訊息主旨:';
$labels['days'] = '天';
$labels['seconds'] = '秒';
$labels['rulestop'] = '停止評估規則';
$labels['enable'] = '啟用/停用';
$labels['filterset'] = '篩選器集合';
$labels['filtersets'] = '篩選器集合';
$labels['filtersetadd'] = '加入篩選器集合';
$labels['filtersetdel'] = '刪除目前的篩選器集合';
$labels['filtersetact'] = '啟用目前的篩選器集合';
$labels['filtersetdeact'] = '停用目前的篩選器集合';
$labels['filterdef'] = '篩選器定義';
$labels['filtersetname'] = '篩選器集合名稱';
$labels['newfilterset'] = '建立篩選器集合';
$labels['active'] = '啟用';
$labels['none'] = '無';
$labels['fromset'] = '從集合';
$labels['fromfile'] = '重檔案';
$labels['filterdisabled'] = '篩選器已停用';
$labels['countisgreaterthan'] = '計數大於';
$labels['countisgreaterthanequal'] = '計數大於或等於';
$labels['countislessthan'] = '計數小於';
$labels['countislessthanequal'] = '數量小於或等於';
$labels['countequals'] = '數量等於';
$labels['valueisgreaterthan'] = '值大於';
$labels['valueisgreaterthanequal'] = '值大於等於';
$labels['valueislessthan'] = '值小於';
$labels['valueislessthanequal'] = '值小於或等於';
$labels['valueequals'] = '值等於';
$labels['setflags'] = '設定標幟';
$labels['addflags'] = '新增標記到訊息';
$labels['removeflags'] = '移除訊息標記';
$labels['flagread'] = '讀取';
$labels['flagdeleted'] = '刪除';
$labels['flaganswered'] = '已經回覆';
$labels['flagflagged'] = '已加標記的郵件';
$labels['flagdraft'] = '草稿';
$labels['setvariable'] = '設定變數';
$labels['setvarname'] = '變數名稱:';
$labels['setvarvalue'] = '變數值:';
$labels['setvarmodifiers'] = '修改:';
$labels['varlower'] = '低於';
$labels['varupper'] = '高於';
$labels['varlowerfirst'] = '第一個字低於';
$labels['varupperfirst'] = '第一個字高於';
$labels['varquotewildcard'] = '跳脫字元';
$labels['varlength'] = '長度';
$labels['notify'] = '寄送通知';
$labels['notifytarget'] = '通知收件人';
$labels['notifymessage'] = '通知內容訊息(選填):';
$labels['notifyoptions'] = '通知項目(選填):';
$labels['notifyfrom'] = '通知寄件人(選填):';
$labels['notifyimportance'] = '重要性:';
$labels['notifyimportancelow'] = '低';
$labels['notifyimportancenormal'] = '一般';
$labels['notifyimportancehigh'] = '高';
$labels['filtercreate'] = '建立郵件規則';
$labels['usedata'] = '於規則中使用轉寄時間';
$labels['nextstep'] = '下一步';
$labels['...'] = '…';
$labels['currdate'] = '現在時間';
$labels['datetest'] = '日期';
$labels['year'] = '年';
$labels['month'] = '月';
$labels['day'] = '日';
$labels['date'] = '日期 (yyyy-mm-dd)';
$labels['julian'] = '日期 (Julian Day)';
$labels['time'] = '時間 (hh:mm:ss)';
$labels['iso8601'] = '日期 (ISO8601)';
$labels['std11'] = '日期 (RFC2822)';
$labels['zone'] = '時區';
$labels['advancedopts'] = '進階選項';
$labels['body'] = '內文';
$labels['address'] = '郵件位址';
$labels['envelope'] = '信封';
$labels['modifier'] = '修改:';
$labels['text'] = '文字';
$labels['undecoded'] = '未解碼(raw)';
$labels['contenttype'] = '內容類型';
$labels['modtype'] = '型態：';
$labels['allparts'] = '全部';
$labels['domain'] = '網域';
$labels['localpart'] = '本機連接埠';
$labels['user'] = '使用者';
$labels['detail'] = '細節';
$labels['comparator'] = '比較:';
$labels['default'] = '預設';
$labels['octet'] = '嚴謹模式(八位元組)';
$labels['asciicasemap'] = '不區分大小寫(採用ASCII-Casemap)';
$labels['asciinumeric'] = '數字類型(ascii-numeric)';
$messages['filterunknownerror'] = '未知的伺服器錯誤';
$messages['filterconnerror'] = '無法與伺服器連線';
$messages['filterdeleted'] = '成功刪除篩選器';
$messages['filtersaved'] = '成功儲存篩選器。';
$messages['filterdeleteconfirm'] = '您確定要刪除選擇的郵件規則嗎?';
$messages['ruledeleteconfirm'] = '您確定要刪除選的規則嗎？';
$messages['actiondeleteconfirm'] = '您確定要刪除選擇的動作嗎？';
$messages['forbiddenchars'] = '內容包含禁用字元';
$messages['cannotbeempty'] = '內容不能為空白';
$messages['ruleexist'] = '規則名稱重複';
$messages['setactivated'] = '篩選器集合成功啟用';
$messages['setdeactivated'] = '篩選器集合成功停用';
$messages['setdeleted'] = '篩選器集合成功刪除';
$messages['setdeleteconfirm'] = '你確定要刪除選擇的篩選器集合嗎？';
$messages['setcreated'] = '篩選器集合成功建立';
$messages['deactivated'] = '篩選器已啟用';
$messages['activated'] = '篩選器已停用';
$messages['moved'] = '篩選器已移動';
$messages['nametoolong'] = '名稱太長。';
$messages['namereserved'] = '保留名稱.';
$messages['setexist'] = '設定已存在';
$messages['nodata'] = '至少要選擇一個位置';
?>
