<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/csv2vcard.inc                                     |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Aleksander Machniak <alec@alec.pl>                            |
 +-----------------------------------------------------------------------+
*/
$map = array();
$map['anniversary'] = "Anniversary";
$map['assistants_name'] = "Assistant's Name";
$map['assistants_phone'] = "Assistant's Phone";
$map['birthday'] = "Birthday";
$map['business_city'] = "Ciudad de trabajo";
$map['business_countryregion'] = "Provincia o estado de trabajo";
$map['business_fax'] = "Business Fax";
$map['business_phone'] = "Teléfono del trabajo";
$map['business_phone_2'] = "Business Phone 2";
$map['business_postal_code'] = "Código postal del trabajo";
$map['business_state'] = "País o región del trabajo";
$map['business_street'] = "Calle del trabajo";
$map['car_phone'] = "Car Phone";
$map['categories'] = "Categorías";
$map['company'] = "Organización";
$map['department'] = "Department";
$map['email_address'] = "E-mail Address";
$map['email_2_address'] = "Dirección de correo electrónico 2";
$map['email_3_address'] = "Dirección del correo electrónico 3";
$map['first_name'] = "Nombre";
$map['gender'] = "Género";
$map['home_city'] = "Home City";
$map['home_countryregion'] = "País o región del domicilio";
$map['home_fax'] = "Home Fax";
$map['home_phone'] = "Particular";
$map['home_phone_2'] = "Home Phone 2";
$map['home_postal_code'] = "Home Postal Code";
$map['home_state'] = "Home State";
$map['home_street'] = "Home Street";
$map['job_title'] = "Puesto";
$map['last_name'] = "Apellidos";
$map['managers_name'] = "Nombre del director";
$map['middle_name'] = "Segundo nombre";
$map['mobile_phone'] = "Mobile Phone";
$map['notes'] = "Notes";
$map['other_city'] = "Otra ciudad";
$map['other_countryregion'] = "Otra provincia o estado";
$map['other_fax'] = "Otro fax";
$map['other_phone'] = "Otro teléfono";
$map['other_postal_code'] = "Otro código postal";
$map['other_state'] = "Otro país o región";
$map['other_street'] = "Otra calle";
$map['pager'] = "Pager";
$map['primary_phone'] = "Teléfono principal";
$map['spouse'] = "Spouse";
$map['suffix'] = "Suffix";
$map['title'] = "Title";
$map['web_page'] = "Página web";
$map['birth_day'] = "Día de nacimiento";
$map['birth_month'] = "Mes de nacimiento";
$map['birth_year'] = "Año de nacimiento";
$map['display_name'] = "Nombre en pantalla";
$map['fax_number'] = "Fax";
$map['home_address'] = "Dirección personal";
$map['home_country'] = "País de residencia";
$map['home_zipcode'] = "Código postal";
$map['mobile_number'] = "Teléfono móvil";
$map['nickname'] = "Apodo";
$map['organization'] = "Organización";
$map['pager_number'] = "Buscapersonas";
$map['primary_email'] = "Dirección de correo electrónico principal";
$map['secondary_email'] = "Dirección de correo electrónico secundaria";
$map['web_page_1'] = "Página web 1";
$map['web_page_2'] = "Página web 2";
$map['work_phone'] = "Teléfono (Trabajo)";
$map['work_address'] = "Dirección de trabajo";
$map['work_country'] = "País (Trabajo)";
$map['work_zipcode'] = "Código postal (Trabajo)";
$map['date_of_birth'] = "Date of Birth";
$map['email'] = "Email";
$map['home_mobile'] = "Home Mobile";
$map['home_zip'] = "Home Zip";
$map['info'] = "Info";
$map['user_photo'] = "User Photo";
$map['url'] = "URL";
$map['work_city'] = "Work City";
$map['work_company'] = "Work Company";
$map['work_dept'] = "Work Dept";
$map['work_fax'] = "Work Fax";
$map['work_mobile'] = "Work Mobile";
$map['work_state'] = "Work State";
$map['work_title'] = "Work Title";
$map['work_zip'] = "Work Zip";
