<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/labels.inc                                        |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/labels/
*/
$labels['welcome']   = 'مرحباً بكم في $product';
$labels['username']  = 'اسم المستخدم';
$labels['password']  = 'كلمة المرور';
$labels['server']    = 'الخادم';
$labels['login']     = 'تسجيل الدخول';
$labels['logout']   = 'تسجيل الخروج';
$labels['mail']     = 'البريد';
$labels['settings'] = 'الإعدادات';
$labels['addressbook'] = 'دفتر العناوين';
$labels['inbox']  = 'البريد الوارد';
$labels['drafts'] = 'المسودات';
$labels['sent']   = 'البريد المرسل';
$labels['trash']  = 'المهملات';
$labels['junk']   = 'الرسائل غير المرغوب فيها';
$labels['subject'] = 'الموضوع';
$labels['from']    = 'المرسل';
$labels['cc']      = 'نسخة إلي';
$labels['bcc']     = 'نسخة مخفية الوجهة';
$labels['date']    = 'التاريخ';
$labels['size']    = 'الحجم';
$labels['priority'] = 'الأولوية';
$labels['mailboxlist'] = 'مجلدات';
$labels['copy']     = 'نسخ';
$labels['move']     = 'نقل';
$labels['moveto']   = 'نقل إلى...';
$labels['download'] = 'تنزيل';
$labels['showattachment'] = 'إظهار';
$labels['showanyway'] = 'إظهار ذلك على أي حال';
$labels['filename'] = 'اسم الملف';
$labels['filesize'] = 'حجم الملف';
$labels['addtoaddressbook'] = 'إضافة إلى دفتر العناوين';
$labels['sun'] = 'أحد';
$labels['mon'] = 'إثنين';
$labels['tue'] = 'ثلاثاء';
$labels['wed'] = 'أربعاء';
$labels['thu'] = 'خميس';
$labels['fri'] = 'جمعة';
$labels['sat'] = 'سبت';
$labels['sunday']    = 'الأحد';
$labels['monday']    = 'الإثنين';
$labels['tuesday']   = 'الثلاثاء';
$labels['wednesday'] = 'الأربعاء';
$labels['thursday']  = 'الخميس';
$labels['friday']    = 'الجمعة';
$labels['saturday']  = 'السبت';
$labels['jan']	= 'يناير';
$labels['feb']	= 'فبراير';
$labels['mar']	= 'مارس';
$labels['apr']	= 'أبريل';
$labels['may']	= 'مايو';
$labels['jun']	= 'يونيو';
$labels['jul'] 	= 'يوليو';
$labels['aug']	= 'أغسطس';
$labels['sep']	= 'سبتمبر';
$labels['oct']	= 'أكتوبر';
$labels['nov']	= 'نوفمبر';
$labels['dec']	= 'ديسمبر';
$labels['longjan']	= 'يناير';
$labels['longfeb']	= 'فبراير';
$labels['longmar']	= 'مارس';
$labels['longapr']	= 'أبريل';
$labels['longmay']	= 'مايو';
$labels['longjun']	= 'يونيو';
$labels['longjul']	= 'يوليو';
$labels['longaug']	= 'أغسطس';
$labels['longsep']	= 'سبتمبر';
$labels['longoct']	= 'أكتوبر';
$labels['longnov']	= 'نوفمبر';
$labels['longdec']	= 'ديسمبر';
$labels['today'] = 'اليوم';
$labels['refresh']          = 'تحديث';
$labels['checkmail']        = 'التحقق من وجود رسائل جديدة';
$labels['compose']          = 'إنشاء';
$labels['writenewmessage']  = 'إنشاء رسالة جديدة';
$labels['reply']            = 'رد';
$labels['replytomessage']   = 'الرد على المرسل';
$labels['replytoallmessage'] = 'الرد على قائمة أو إلى المرسل وجميع المستلمين';
$labels['replyall']         = 'الرد على الجميع';
$labels['replylist']        = 'الرد على القائمة';
$labels['forward']          = 'إعادة توجيه';
$labels['deletemessage']    = 'حذف الرسالة';
$labels['movemessagetotrash'] = 'انقل الرسالة إلى سلة المهملات';
$labels['printmessage']     = 'أطبع هذه الرسالة';
$labels['previousmessage']  = 'عرض الرسالة السابقة';
$labels['firstmessage']     = 'عرض الرسالة الأولى';
$labels['nextmessage']      = 'عرض الرسالة التالية';
$labels['lastmessage']      = 'عرض الرسالة الأخيرة';
$labels['backtolist']       = 'العودة إلى قائمة الرسائل';
$labels['viewsource']       = 'إظهار المصدر';
$labels['mark']             = 'علامة';
$labels['markread']         = 'مقروءة';
$labels['markunread']       = 'غير مقروءة';
$labels['moreactions']      = 'إجراءات إضافية...';
$labels['more']             = 'المزيد';
$labels['back']             = 'العودة';
$labels['options']          = 'خيارات';
$labels['select'] = 'تحديد';
$labels['all'] = 'الكل';
$labels['none'] = 'لاشيء';
$labels['currpage'] = 'الصفحة الحالية';
$labels['unread'] = 'غير مقروءة';
$labels['flagged'] = 'موسوم';
$labels['unanswered'] = 'بلا رد';
$labels['deleted'] = 'محذوف';
$labels['undeleted'] = 'غير محذوفة';
?>
