<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/userinfo/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/
$labels['userinfo'] = 'ព័ត៌មាន​អ្នក​ប្រើ';
$labels['created'] = 'បាន​បង្កើត';
$labels['lastlogin'] = 'ចូល​ចុងក្រោយ';
$labels['defaultidentity'] = 'អត្តសញ្ញាណ​លំនាំដើម';
?>