<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/userinfo/localization/<lang>.inc                              |
 |                                                                       |
 | Localization file of the Roundcube Webmail Userinfo plugin            |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-userinfo/
*/
$labels['userinfo'] = 'ഉപയോക്താവിന്റെ വിവരം';
$labels['created'] = 'നിര്‍മ്മിച്ചു';
$labels['lastlogin'] = 'അവസാന പ്രവേശനം';
$labels['defaultidentity'] = 'സാധാരണ വ്യക്തിത്വം';
?>