<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Villa kom upp!';
$messages['loginfailed']  = 'Innskráning mistókst';
$messages['cookiesdisabled'] = 'Vafrinn þinn vill ekki taka við kökum (cookies)';
$messages['sessionerror'] = 'Innskráningin þín ógild eða útrunnin';
$messages['storageerror'] = 'Tengin við IMAP-miðlara mistókst';
$messages['servererror'] = 'Villa í þjóni!';
$messages['servererrormsg'] = 'Villa í þjóni: $msg';
$messages['accountlocked'] = 'Of margar tilraunir til innskráningar. Reyndu aftur síðar.';
$messages['connerror'] = 'Villa í tengingu (mistókst að ná í þjóninn)!';
$messages['dberror'] = 'Villa í gagnagrunni!';
$messages['windowopenerror'] = 'Lokað var á sprettgluggann!';
$messages['requesttimedout'] = 'Fyrirspurn féll á tíma';
$messages['errorreadonly'] = 'Tókst ekki að framkvæma aðgerð. Mappa er skrifvarin.';
$messages['errornoperm'] = 'Tókst ekki að framkvæma aðgerð. Heimild var hafnað.';
$messages['erroroverquota'] = 'Tókst ekki að framkvæma aðgerð. Ekkert laust diskpláss.';
$messages['erroroverquotadelete'] = 'Ekki nægt laust diskpláss. Notaðu SHIFT+DEL til að eyða skeyti.';
$messages['invalidhost'] = 'Ógilt heiti á þjóni.';
$messages['nomessagesfound'] = 'Engin skeyti eru í þessu pósthólfi';
$messages['loggedout'] = 'Þú hefur lokað setunni. Bless í bili!';
$messages['mailboxempty'] = 'Pósthólf er tómt';
$messages['nomessages'] = 'Engin skeyti';
$messages['refreshing'] = 'Endurles...';
$messages['loading'] = 'Hleð...';
$messages['uploading'] = 'Sendi inn skrá...';
$messages['attaching'] = 'Hengi við skrá...';
$messages['uploadingmany'] = 'Sendi inn skrár...';
$messages['loadingdata'] = 'Hleð inn gögnum...';
$messages['checkingmail'] = 'Athuga með ný skeyti...';
$messages['sendingmessage'] = 'Sendi skeyti...';
$messages['messagesent'] = 'Skeytið var sent.';
$messages['savingmessage'] = 'Vista skeyti...';
$messages['messagesaved'] = 'Skeytið vistað í Drög.';
$messages['successfullysaved'] = 'Vistun heppnaðist!';
$messages['savingresponse'] = 'Vista texta svars...';
$messages['deleteresponseconfirm'] = 'Ertu viss um að þú viljir eyða þessum svartexta?';
$messages['addedsuccessfully'] = 'Netfangi var bætt í netfangaskrá.';
$messages['contactnameexists'] = 'Tengiliður með sama nafn er þegar skráður í netfangaskrána.';
$messages['blockedimages'] = 'Til verndar hafa allar myndir í þessu skeyti verið blokkaðar.';
$messages['encryptedmessage'] = 'Þetta er dulkóðað skeyti og því miður er ekki hægt að birta það';
$messages['nopubkeyfor'] = 'Enginn gildur dreifilykill fannst fyrir $email';
$messages['keyservererror'] = 'Mistókst að nálgast lykil á lyklaþjóni';
$messages['nocontactsfound'] = 'Engir tengiliðir fundust.';
$messages['contactnotfound'] = 'Umbeðinn tengiliður fannst ekki.';
$messages['contactsearchonly'] = 'Settu inn leitartexta til að finna tengiliði';
$messages['sendingfailed'] = 'Sending misheppnaðist.';
$messages['errorsaving'] = 'Villa kom upp við vistun.';
$messages['errormoving'] = 'Gat ekki fært skeytið';
$messages['errorcopying'] = 'Gat ekki afritað skeyti(n).';
$messages['errordeleting'] = 'Gat ekki eytt skeytinu';
$messages['errormarking'] = 'Gat ekki merkt skeytið/skeytin.';
$messages['deletecontactconfirm']  = 'Ertu viss um að þú viljir eyða völdum tengiliðum?';
$messages['deletegroupconfirm']  = 'Ertu viss um að þú viljir eyða völdum hópi?';
$messages['deletemessagesconfirm'] = 'Ertu viss um að þú viljir eyða völdum skeytum?';
$messages['deletefolderconfirm']  = 'Ertu viss um að vilja eyða þessari möppu?';
$messages['purgefolderconfirm']  = 'Ertu viss um að þú viljir eyða öllum skeytum í þessari möppu?';
$messages['contactdeleting'] = 'Eyði tengilið(um)...';
$messages['groupdeleting'] = 'Eyði hóp...';
$messages['folderdeleting'] = 'Eyði möppu...';
$messages['foldermoving'] = 'Færi möppu...';
$messages['foldersubscribing'] = 'Tek möppu í áskrift...';
$messages['folderunsubscribing'] = 'Segi upp áskrift að möppu...';
$messages['formincomplete'] = 'Formið var ekki fyllt út að fullu';
$messages['noemailwarning'] = 'Sláðu inn gildt netfang';
$messages['nonamewarning']  = 'Sláðu inn nafn';
$messages['nopagesizewarning'] = 'Sláðu inn síðustærð';
$messages['nosenderwarning'] = 'Settu inn tölvupóstfang sendanda.';
$messages['norecipientwarning'] = 'Í það minnsta einn viðtakandi verður að vera';
$messages['nosubjectwarning']  = 'Efnislínan er tóm. Viltu slá eitthvað inn í hana?';
$messages['nobodywarning'] = 'Viltu senda tómt skeyti?';
$messages['notsentwarning'] = 'Skeytið hefur ekki verið send. Viltu henda skeytinu?';
$messages['noldapserver'] = 'Please select an ldap server to search';
$messages['nosearchname'] = 'Sláðu inn nafn eða netfang';
$messages['searchsuccessful'] = '$nr skeyti fundust';
$messages['contactsearchsuccessful'] = '$nr tengiliðir fundust.';
$messages['searchnomatch'] = 'Leit skilaði engu';
$messages['searching'] = 'Leita...';
$messages['checking'] = 'Gái...';
$messages['stillsearching'] = 'Enn að leita...';
$messages['nospellerrors'] = 'Engar innsláttarvillur fundust';
$messages['folderdeleted'] = 'Möppu var eytt';
$messages['deletedsuccessfully'] = 'Tókst að eyða.';
$messages['filelinkerror'] = 'Mistókst að hengja við skrá.';
$messages['movingmessage'] = 'Færi skeyti...';
$messages['copyingmessage'] = 'Afrita skeyti...';
$messages['copyingcontact'] = 'Afrita tengiliði...';
$messages['movingcontact'] = 'Færi tengiliði...';
$messages['deletingmessage'] = 'Eyði skeytum...';
$messages['markingmessage'] = 'Merki skeyti...';
$messages['addingmember'] = 'Bæti tengiliðum í hópinn...';
$messages['removingmember'] = 'Fjarlægi tengiliði úr hópi...';
$messages['importwait'] = 'Flyt inn, bíddu aðeins...';
$messages['importmessagesuccess'] = 'Tókst að flytja inn $nr skeyti';
$messages['smtperror'] = 'SMTP villa: $msg';
$messages['emailformaterror'] = 'Ógilt tölvupóstfang: $email';
$messages['contactdelerror'] = 'Gat ekki eytt tengilið(um).';
$messages['contactdeleted'] = 'Tókst að eyða tengilið(um).';
$messages['messagedeleted'] = 'Tókst að eyða skeyti/skeytum.';
$messages['messagemoved'] = 'Tókst að færa skeyti.';
$messages['messagecopied'] = 'Tókst að afrita skeyti.';
$messages['messagemarked'] = 'Tókst að merkja skeyti.';
$messages['namecannotbeempty'] = 'Nafn má ekki vera autt.';
$messages['nametoolong'] = 'Nafn er of langt.';
$messages['namedotforbidden'] = 'Heiti möppu má ekki byrja á punkti.';
$messages['folderupdated'] = 'Tókst að uppfæra möppu';
$messages['foldercreated'] = 'Tókst að búa til möppu.';
$messages['invalidimageformat'] = 'Ekki gilt myndasnið.';
$messages['errnotfound'] = 'Skrá fannst ekki';
$messages['errfailedrequest'] = 'Beiðni misfórst';
$messages['errauthorizationfailed'] = 'Auðkenning mistókst';
$messages['errcontactserveradmin'] = 'Hafðu samband við kerfisstjóra þjónsins þíns';
$messages['clicktoresumesession'] = 'Smelltu hér til að halda áfram með fyrri setu';
$messages['clicktocompose'] = 'Smelltu hér til að búa til nýtt skeyti';
