<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/emoticons/localization/<lang>.inc                             |
 |                                                                       |
 | Localization file of the Roundcube Webmail Emoticons plugin           |
 | Copyright (C) 2012-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-emoticons/
*/

$labels = array();
$labels['emoticonsdisplay'] = 'Display emoticons in plain text messages';
$labels['emoticonscompose'] = 'Enable emoticons';

?>
