<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/help/localization/<lang>.inc                                  |
 |                                                                       |
 | Localization file of the Roundcube Webmail Help plugin                |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-help/
*/
$labels['help'] = 'Помощь';
$labels['about'] = 'О программе';
$labels['license'] = 'Лицензия';
$labels['csrfinfo'] = 'Узнайте больше о CSRF и о том как мы защищаем вас';
?>
