<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Ee Feeler ass opgetrueden!';
$messages['loginfailed']  = 'Login feelgeschloen.';
$messages['cookiesdisabled'] = 'Däi Browser acceptéiert keng Cookien.';
$messages['sessionerror'] = 'Deng Sessioun ass ongëlteg oder verfall.';
$messages['storageerror'] = 'D\'Verbindung mam Späicher-Server ass feelgeschloen.';
$messages['servererror'] = 'Server-Feeler!';
$messages['servererrormsg'] = 'Server-Feeler: $msg';
$messages['connerror'] = 'Connectiouns-Feeler (De Server konnt net erreecht ginn)!';
$messages['dberror'] = 'Datebank-Feeler!';
$messages['windowopenerror'] = 'D\'Popup-Fënster gouf blockéiert!';
$messages['requesttimedout'] = 'D\'Ufro huet ze laang gedauert';
$messages['errorreadonly'] = 'D\'Operatioun kann net ofgeschloss ginn. Den Dossier ass schreifgeschützt.';
$messages['errornoperm'] = 'D\'Operatioun kann net ofgeschloss ginn. Zougrëff verweigert.';
$messages['erroroverquota'] = 'D\'Operatioun konnt net ausgefouert ginn. Et ass net méi genuch Plaz um Disk.';
$messages['erroroverquotadelete'] = 'Et ass net méi genuch Plaz um Disk. Benotz Shift+Delete fir e message ze läschen.';
$messages['invalidrequest'] = 'Ongëlteg Ufro! Et goufe keng Date gespäichert.';
$messages['invalidhost'] = 'Ongëltege Server-Numm.';
$messages['nomessagesfound'] = 'Keng Messagen an der Mailbox fonnt.';
$messages['loggedout'] = 'Du hues dech erfollegräich ofgemellt. Äddi!';
$messages['mailboxempty'] = 'D\'Mailbox ass eidel';
$messages['nomessages'] = 'Keng Messagen';
$messages['refreshing'] = 'Lueden nei...';
$messages['loading'] = 'Lueden...';
$messages['uploading'] = 'Fichier gëtt eropgelueden...';
$messages['uploadingmany'] = 'Fichiere ginn eropgelueden...';
$messages['loadingdata'] = 'Date gi gelueden..';
$messages['checkingmail'] = 'Nei Messagë ginn ofgeruff...';
$messages['sendingmessage'] = 'Message gëtt geschéckt...';
$messages['messagesent'] = 'Message erfollegräich verschéckt.';
$messages['savingmessage'] = 'Message gëtt gespäichert...';
$messages['messagesaved'] = 'Message als Brouillon gespäichert.';
$messages['successfullysaved'] = 'Erfollegräich gespäichert.';
$messages['savingresponse'] = 'Äntwert-Text gëtt gespäichert...';
$messages['deleteresponseconfirm'] = 'Wëlls du dësen Äntwert-Text wierklech läschen?';
$messages['addedsuccessfully'] = 'Kontakt erfollegräich an d\'Adressbuch gesat.';
$messages['contactnameexists'] = 'Et existéiert schon e Kontakt mam selweschten Numm.';
$messages['blockedimages'] = 'Fir deng Privatsphär ze schütze, gi Biller vun externe Serveren an dësem Message net gelueden.';
$messages['encryptedmessage'] = 'Dëst ass e verschlësselte Message a kann net ugewise ginn. Et deet eis Leed!';
$messages['nocontactsfound'] = 'Keng Kontakter fonnt.';
$messages['contactnotfound'] = 'Den ugefrotene Kontakt gouf net fonnt.';
$messages['contactsearchonly'] = 'Gëff e puer Sichbegrëffer a fir Kontakter ze fannen';
$messages['sendingfailed'] = 'De Message konnt net verschéckt ginn.';
$messages['senttooquickly'] = 'Waart wann ech gelift $sec Sekonn(en) bevir s du de Message verschécks. ';
$messages['errorsavingsent'] = 'Beim Späichere vum geschéckte Message ass e Feeler opgetruden.';
$messages['errorsaving'] = 'Beim Späicheren ass e Feeler opgetrueden.';
$messages['errormoving'] = 'D\'Messagë konnten net verréckelt ginn.';
$messages['errorcopying'] = 'D\'Messagë konnten net kopéiert ginn.';
$messages['errordeleting'] = 'D\'Messagë konnten net geläscht ginn.';
$messages['errormarking'] = 'D\'Messagë konnten net markéiert ginn.';
$messages['deletecontactconfirm']  = 'Wëlls du wierklech déi ausgewielte Kontakter läschen?';
$messages['deletegroupconfirm']  = 'Wëlls du wierklech déi ausgewielte Gruppe läschen?';
$messages['deletemessagesconfirm'] = 'Wëlls du wierklech déi ausgewielte Messagë läschen?';
$messages['deletefolderconfirm']  = 'Wëlls du dësen Dossier wierklech läschen?';
$messages['purgefolderconfirm']  = 'Wëlls du wierklech all d\'Messagen an dësem Dossier läschen?';
$messages['contactdeleting'] = 'Kontakter gi geläscht...';
$messages['groupdeleting'] = 'Grupp gëtt geläscht...';
$messages['folderdeleting'] = 'Dossier gëtt geläscht...';
$messages['foldermoving'] = 'Dossier gëtt geréckelt...';
$messages['foldersubscribing'] = 'Dossier gëtt abonnéiert...';
$messages['folderunsubscribing'] = 'Dossier gëtt desabonnéiert...';
$messages['formincomplete'] = 'De Formular war net komplett ausgefëlt.';
$messages['noemailwarning'] = 'Gëff w.e.gl eng gëlteg Email-Adress an.';
$messages['nonamewarning']  = 'Gëff w.e.gl en Numm an.';
$messages['nopagesizewarning'] = 'Gëff w.e.gl eng Säitegréisst an.';
$messages['norecipientwarning'] = 'Gëff w.e.gl op mannst een Empfänger an.';
$messages['nosubjectwarning']  = 'D\'Feld "Sujet" ass eidel. Wëlls du elo eent uginn?';
$messages['nobodywarning'] = 'Soll dëse Message ouni Text verschéckt ginn?';
$messages['notsentwarning'] = 'De Message gouf net verschéckt. Wëlls du e verwerfen?';
$messages['restoresavedcomposedata'] = 'Et gouf e Message fonnt dee scho geschriwwen awer nach net verschéckt ginn ass.\n\nSujet: $subject\nGespäichert: $date\n\nSoll de Message recuperéiert ginn?';
$messages['noldapserver'] = 'Wiel w.e.gl en LDAP-Server fir d\'Sich aus.';
$messages['nosearchname'] = 'Gëff w.e.gl en Numm oder eng E-Mail-Adress fir de Kontakt an.';
$messages['notuploadedwarning'] = 'Net all d\'Unhäng goufen eropgelueden. Waart w.e.gl e Moment oder briech den Upload of.';
$messages['searchsuccessful'] = '$nr Messagë fonnt.';
$messages['contactsearchsuccessful'] = '$nr Kontakter fonnt.';
$messages['searchnomatch'] = 'D\'Sich huet keng Treffer bruecht.';
$messages['searching'] = 'Sichen...';
$messages['checking'] = 'Kontrolléieren...';
$messages['stillsearching'] = 'D\'Sich leeft nach...';
$messages['nospellerrors'] = 'Et goufe keng Schreiffeeler fonnt.';
$messages['folderdeleted'] = 'Dossier erfollegräich geläscht.';
$messages['foldersubscribed'] = 'Dossier erfollegräich abonnéiert.';
$messages['folderunsubscribed'] = 'Dossier erfollegräich desabonnéiert.';
$messages['folderpurged'] = 'Dossier erfollegräich eidelgemaach.';
$messages['folderexpunged'] = 'Dossier erfollegräich kompaktéiert.';
$messages['deletedsuccessfully'] = 'Erfollegräich geläscht.';
$messages['converting'] = 'Formatéierunge gi geläscht...';
$messages['messageopenerror'] = 'Message konnt net vum Server geluede ginn.';
$messages['fileuploaderror'] = 'Upload vum Fichier feelgeschloen.';
$messages['filesizeerror'] = 'Den eropgeluedene Fichier ass méi grouss wéi déi maximal erlaabte Gréisst vun $size.';
$messages['copysuccess'] = 'Et goufen erfollegräich $nr Kontakter kopéiert.';
$messages['movesuccess'] = 'Et goufen erfollegräich $nr Kontakter geréckelt.';
$messages['copyerror'] = 'Konnt d\'Kontakter net kopéieren';
$messages['moveerror'] = 'Konnt d\'Kontakter net réckelen.';
$messages['sourceisreadonly'] = 'D\'Adresse-Quell ass schreifgeschützt.';
$messages['errorsavingcontact'] = 'D\'Kontakt-Adress konnt net gespäichert ginn.';
$messages['movingmessage'] = 'Messagë gi geréckelt...';
$messages['copyingmessage'] = 'Messagë gi kopéiert...';
$messages['copyingcontact'] = 'Kontakter gi kopéiert...';
$messages['movingcontact'] = 'Kontakter gi geréckelt...';
$messages['deletingmessage'] = 'Messagë gi geläscht...';
$messages['markingmessage'] = 'Messagë gi markéiert...';
$messages['addingmember'] = 'Kontakter ginn an d\'grupp gesat...';
$messages['removingmember'] = 'Kontakter ginn aus der Grupp erausgeholl...';
$messages['receiptsent'] = 'Empfanksbestätegung erfollegräich verschéckt.';
$messages['errorsendingreceipt'] = 'Konnt d\'Bestätegung net verschécken.';
$messages['deleteidentityconfirm'] = 'Wëlls du dës Identitéit wierklech läschen?';
$messages['nodeletelastidentity'] = 'Du kanns dës Identitéit net läschen, well et deng lescht ass.';
$messages['forbiddencharacter'] = 'Den Numm vum Dossier enthält verbueden Zeechen.';
$messages['selectimportfile'] = 'Wuel w.e.gl e Fichier aus fir eropzelueden.';
$messages['addresswriterror'] = 'Dat ausgewieltent Adressbucht ass schreifgeschützt.';
$messages['contactaddedtogroup'] = 'Kontakter erfollegräich an d\'Grupp gesat.';
$messages['contactremovedfromgroup'] = 'Kontakter erfollegräich aus der Grupp erausgeholl.';
$messages['nogroupassignmentschanged'] = 'Keng Gruppen-Zouuerdnung geännert.';
$messages['importwait'] = 'Import leeft, ee Moment w.e.gl...';
$messages['importformaterror'] = 'Import feelgeschloen! Den eropgeluedene Fichier ass kee gëltegen Date-Fichier.';
$messages['importconfirm'] = '<b>$inserted Kontakter erfollegräich importéiert</b>';
$messages['importconfirmskipped'] = '<b>$skipped existéierend Anträg iwwersprongen</b>';
$messages['importmessagesuccess'] = 'Erfollegräich $nr Messagen importéiert';
$messages['importmessageerror'] = 'Import feelgeschloen! Den eropgeluedene Fichier ass kee gëltege Message oder kee Mailbox-Fichier.';
$messages['opnotpermitted'] = 'Operatioun net zougelooss!';
$messages['editorwarning'] = 'Den Editor-Typ ze wiessele kann de Verloscht vun Textformatéierunge verursaachen. Wëlls du weidermaachen?';
$messages['httpreceivedencrypterror'] = 'E fatale Konfiguratiouns-Feeler ass opgetrueden. Kontaktéier w.e.gl. den Administrator esou séier ewéi méiglech. <b>Däi Message kann net geschéckt ginn.</b> ';
$messages['smtpconnerror'] = 'SMTP-Feeler ($code): Et konnt keng Verbindung mam Server hirgestallt ginn.';
$messages['smtpautherror'] = 'SMTP-Feeler ($code): Authentifizéierung feelgeschloen.';
$messages['smtpfromerror'] = 'SMTP-Feeler ($code): Den Ofsender "$from" konnt net gesat ginn ($msg).';
$messages['smtptoerror'] = 'SMTP-Feeler ($code): Den Empfänger "$to" konnt net dobäigesat ginn ($msg).';
$messages['smtprecipientserror'] = 'SMTP-Feeler: D\'Empfänger-Lëscht kann net verschafft ginn.';
$messages['smtperror'] = 'SMTP-Feeler: $msg';
$messages['toomanyrecipients'] = 'Zevill Empfänger. Reduzéier d\'Zuel vun den Empfänger op $max.';
$messages['maxgroupmembersreached'] = 'D\'Unzuel vu Gruppememberen iwwersteigt de Maximum vun $max.';
$messages['internalerror'] = 'En interne Feeler ass opgetrueden. Probéier w.e.gl nach eng Kéier.';
$messages['contactdelerror'] = 'Kontakter konnten net geläscht ginn.';
$messages['contactdeleted'] = 'Kontakter erfollegräich geläscht.';
$messages['contactrestoreerror'] = 'Déi geläschte Kontakter konnten net recuperéiert ginn.';
$messages['contactrestored'] = 'Kontakter erfollegräich recuperéiert.';
$messages['groupdeleted'] = 'Grupp erfollegräich geläscht.';
$messages['grouprenamed'] = 'Grupp erfollegräich ëmbenannt.';
$messages['groupcreated'] = 'Grupp erfollegräich creéiert.';
$messages['savedsearchdeleted'] = 'Déi gespäicherte Sich gouf erfollegräich geläscht.';
$messages['savedsearchdeleteerror'] = 'Déi gespäicherte Sich konnt net geläscht ginn.';
$messages['savedsearchcreated'] = 'Déi gespäicherte Sich gouf erfollegräich erstallt.';
$messages['savedsearchcreateerror'] = 'Déi gespäicherte Sich konnt net erstallt ginn.';
$messages['messagedeleted'] = 'Messagen erfollegräich geläscht.';
$messages['messagemoved'] = 'Messagen erfollegräich geréckelt.';
$messages['messagecopied'] = 'Messagen erfollegräich kopéiert.';
$messages['messagemarked'] = 'Messagen erfollegräich markéiert.';
$messages['autocompletechars'] = 'Gëff e mimumum vun $min Zeechen u fir déi automatesch Vervollstänegung.';
$messages['autocompletemore'] = 'Et goufe méi passend Treffer fonnt. Tipp w.e.gl. nach e puer Buschtawe méi.';
$messages['namecannotbeempty'] = 'Den Numm kann net eidel sinn.';
$messages['nametoolong'] = 'Den Numm ass ze laang.';
$messages['folderupdated'] = 'Dossier erfollegräich aktualiséiert.';
$messages['foldercreated'] = 'Dossier erfollegräich ugeluecht.';
$messages['invalidimageformat'] = 'Kee gëltegt Bild-Format';
$messages['mispellingsfound'] = 'Et goufe Schreiffeeler am Message fonnt.';
$messages['parentnotwritable'] = 'Den Dossier konnt net am ausgewielten Dossier erstallt oder an den Dossier erageréckelt ginn. Keng Zougrëffsrechter.';
$messages['messagetoobig'] = 'Den Messagen-Deel ass ze grouss fir verschafft ze ginn.';
$messages['attachmentvalidationerror'] = 'WARNUNG! Dësen Unhank ass verdächteg well den tatsächlechen Typ vum Fichier net mam Typ deen am Message deklaréiert ass iwwertenee stëmmt. Falls du dem Ofsender net traus sollts du den Unhank net am Browser opmaache well e béisaartegen Inhalt enthaale kéint.<br/><br/><em>Erwaart: $expected; fonnt: $detected</em>';
$messages['noscriptwarning'] = 'Warnung: Dëse Webmail brauch JavaScript! Fir de Service benotzen ze kënnen, aktivéier w.e.gl JavaScript an denge Browser-Astellungen.';
