<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Xatolik yuzaga keldi!';
$messages['loginfailed']  = 'Kirish amalga oshirilmadi.';
$messages['cookiesdisabled'] = 'Brauzeringiz kukilarni qabul qilmaydi.';
$messages['sessionerror'] = 'Sizning sessiyangiz noto‘g‘ri yoki muddati tugagan.';
$messages['storageerror'] = 'Xotira serveriga bog‘lanib bo‘lmadi.';
$messages['servererror'] = 'Server xatosi!';
$messages['servererrormsg'] = 'Server xatosi: $msg';
$messages['connerror'] = 'Ulanishda xato (server bilan bog‘lanib bo‘lmadi)!';
$messages['dberror'] = 'Ma’lumotlar ombori xatosi!';
$messages['windowopenerror'] = 'Sakrab chiquvchi oyna bloklangan!';
$messages['requesttimedout'] = 'So‘rov vaqti tugadi';
$messages['errorreadonly'] = 'Amalni bajarib bo‘lmadi. Jild faqat o‘qish uchun.';
$messages['errornoperm'] = 'Amalni bajarib bo‘lmadi. Ruxsat berilmagan.';
$messages['erroroverquota'] = 'Amalni bajarib bo‘lmadi. Bo‘sh joy qolmagan.';
$messages['erroroverquotadelete'] = 'Bo‘sh joy qolmagan. SHIFT+DEL ni bosib, xabarni o‘chirib tashlang.';
$messages['invalidrequest'] = 'Noto‘g‘ri so‘rov! Ma’lumot saqlanmadi.';
$messages['invalidhost'] = 'Server nomi noto‘g‘ri.';
$messages['nomessagesfound'] = 'Bu pochta qutisida xabarlar topilmadi.';
$messages['mailboxempty'] = 'Pochta qutisi bo‘sh';
$messages['nomessages'] = 'Xabarlar yo‘q';
$messages['refreshing'] = 'Yangilanmoqdau2026';
$messages['loading'] = 'Iltimos, kuting…';
$messages['uploading'] = 'Fayl yuklanmoqdau2026';
$messages['uploadingmany'] = 'Fayllar yuklanmoqdau2026';
$messages['loadingdata'] = 'Ma’lumotlar yuklanmoqdau2026';
$messages['checkingmail'] = 'Yangi xabarlar tekshirilmoqdau2026';
$messages['sendingmessage'] = 'Xabar yuborilmoqda…';
$messages['messagesent'] = 'Xabar muvaffaqiyatli yuborildi.';
$messages['savingmessage'] = 'Xabar saqlanmoqda…';
$messages['messagesaved'] = 'Xabar qoralamalarga saqlanda';
$messages['successfullysaved'] = 'Muvaffaqiyatli saqlandi.';
$messages['savingresponse'] = 'Javob matni saqlanmoqdau2026';
$messages['deleteresponseconfirm'] = 'Siz rostdan ham bu javob xatini o‘chirmoqchimisiz?';
$messages['addedsuccessfully'] = 'Manzillar kitobiga kontakt qo‘shildi.';
