<?php

/*
 +-----------------------------------------------------------------------+
 | localization/<lang>/messages.inc                                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail client                     |
 | Copyright (C) 2005-2015, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/messages/
*/
$messages['errortitle']  = 'Xəta baş verdi!';
$messages['loginfailed']  = 'Giriş uğursuz oldu.';
$messages['cookiesdisabled'] = 'Sizin brauzer kukiləri qəbul etmir.';
$messages['sessionerror'] = 'Sizin sessiya köhnəlib.';
$messages['storageerror'] = 'IMAP serverlə bağlantı alınmadı.';
$messages['servererror'] = 'Server Xətası!';
$messages['servererrormsg'] = 'Server Xətası: $msg';
$messages['dberror'] = 'Məlumatlar Bazasında Xəta!';
$messages['requesttimedout'] = 'Sorğunun gözləmə müddəti bitdi';
$messages['errorreadonly'] = 'Əməliyyatı icra etmək mümkün deyil. Qovluq yalnız oxunuş üçündür.';
$messages['errornoperm'] = 'Əməliyyatı etmək mümkün deyil. Giriş qadağandır.';
$messages['erroroverquota'] = 'Əməliyyat icra edilə bilinmir. Boş disk həcmi yoxdur.';
$messages['erroroverquotadelete'] = 'Boş disk həcmi yoxdur. Məktubu silmək üçün SHIFT+DEL düyməsini istifadə edin.';
$messages['invalidrequest'] = 'Səhv sorğu! Məlumat yaddaşda qalmadı.';
$messages['invalidhost'] = 'Səhv server adı.';
$messages['nomessagesfound'] = 'Poçt qutusunda məktub tapılmadı.';
$messages['loggedout'] = 'Çıxış uğurlu oldu. Sağ olun!';
$messages['mailboxempty'] = 'Poçt boşdur';
$messages['nomessages'] = 'Məktub yoxdur';
$messages['refreshing'] = 'Yenilənmə...';
$messages['loading'] = 'Yüklənir...';
$messages['uploading'] = 'Fayl yüklənir...';
$messages['uploadingmany'] = 'Fayllar yüklənir...';
$messages['loadingdata'] = 'Məlumatlar yüklənir...';
$messages['checkingmail'] = 'Yeni məktubları yoxla...';
$messages['sendingmessage'] = 'Məktub göndərilir...';
$messages['messagesent'] = 'Məktub uğurla göndərildi';
$messages['savingmessage'] = 'Məktubu saxla...';
$messages['messagesaved'] = 'Məktub qaralamada saxlandı';
$messages['successfullysaved'] = 'Yaddaşa yazıldı';
$messages['savingresponse'] = 'Cavab mətninin saxlanılması...';
$messages['deleteresponseconfirm'] = 'Siz cavab mətnini silmək istəyirsiniz?';
$messages['addedsuccessfully'] = 'Əlaqə ünvan kitabçasına əlavə olundu';
$messages['contactnameexists'] = 'Bu adda kontakt artıq mövcuddur.';
$messages['blockedimages'] = 'Təhlükəsizlik məqsədi ilə şəkillərin yüklənməsi bloklanıb.';
$messages['encryptedmessage'] = 'Məktub şifrələnib və göstərilə bilməz. Server inzibatçısına müraciət edin.';
$messages['nocontactsfound'] = 'Ünvanlar tapılmadı';
$messages['contactnotfound'] = 'Tələb olunan ünvan tapılmadı';
$messages['contactsearchonly'] = 'Kontaqların axtarışı üçün şərti daxil edin';
$messages['sendingfailed'] = 'Məktub göndərilmədi';
$messages['senttooquickly'] = 'Məktub göndərmək üçün $sec saniyə gözləmək gərəkir';
$messages['errorsavingsent'] = 'Göndərilən məktubun saxlanılması zamanı xəta baş verdi.';
$messages['errorsaving'] = 'Saxlanılma zamanı xəta baş verdi.';
$messages['errormoving'] = 'Məktubu (məktubları) köçürmək alnmadı';
$messages['errorcopying'] = 'Məktubu (məktubları) kopyalamaq alınmadı';
$messages['errordeleting'] = 'Məktubu (məktubları) silmək alınmadı';
$messages['errormarking'] = 'Məktubu (məktubları) işarələmək mümkün deyil';
$messages['deletecontactconfirm']  = 'Seçilən ünvanı (ünvanları) silməyə əminsiniz?';
$messages['deletegroupconfirm']  = 'Qrupu silməkdə əminsiniz?';
$messages['deletemessagesconfirm'] = 'Seçilən məktubu (məktubları) silməyə əminsiniz?';
$messages['deletefolderconfirm']  = 'Bu qovluğu silməyə əminsiniz?';
$messages['purgefolderconfirm']  = 'Bu qovluqdakı bütün məktubları silməyə əminsiniz?';
$messages['contactdeleting'] = 'Kontak(lar)ın silinməsi...';
$messages['groupdeleting'] = 'Qrupun silinməsi...';
$messages['folderdeleting'] = 'Qovluğ silinir...';
$messages['foldermoving'] = 'Qovluq köçürülür...';
$messages['foldersubscribing'] = 'Qovluğa abunə...';
$messages['folderunsubscribing'] = 'Qovluğa abunədən çıx...';
$messages['formincomplete'] = 'Bütün sətrlər doldurulmayıb';
$messages['noemailwarning'] = 'Lütfən, düzgün e-poçt ünvanı daxil edin';
$messages['nonamewarning']  = 'Lütfən, ad daxil edin';
$messages['nopagesizewarning'] = 'Lütfən, səhifənin ölçüsünü daxil edin';
$messages['norecipientwarning'] = 'Lütfən, qəbul edənin ünvanını daxil edin';
$messages['nosubjectwarning']  = '"Mövzu" sahəsi boşdur. Mövzu daxil etmək istəyirsiniz?';
$messages['nobodywarning'] = 'Məktub boş göndərilsin?';
$messages['notsentwarning'] = 'Məktub göndərilmədi. Göndərilmədən imtina etmək istəyirsiniz?';
$messages['restoresavedcomposedata'] = 'Əvvəlki göndərildi, ancaq göndərilməyən məktub da tapıldı.\n\nSubject: $subject\nSaved: $date\n\nSiz bu məktubu bərpa etmək istəyirsiniz?';
$messages['noldapserver'] = 'Lütfən, axtarış üçün LDAP server seçin';
$messages['nosearchname'] = 'Lütfən, ad və ya e-poçt əlavə edin';
$messages['notuploadedwarning'] = 'Əlavələr tam yüklənilməyib. Gözləyin və ya yükləməni ləğv edin.';
$messages['searchsuccessful'] = 'Tapılan məktublar: $nr';
$messages['contactsearchsuccessful'] = '$nr kontakt tapılıb.';
$messages['searchnomatch'] = 'Məktub tapılmadı';
$messages['searching'] = 'Axtarılır...';
$messages['checking'] = 'Yoxlanılır...';
$messages['nospellerrors'] = 'Orfoqrafik səhvlət tapılmadı';
$messages['folderdeleted'] = 'Qovluq uğurla silindi';
$messages['foldersubscribed'] = 'Qovluq uğurla abunə oldu';
$messages['folderunsubscribed'] = 'Qovluq uğurla abunədən çıxdı';
$messages['folderpurged'] = 'Qovluq uğurla təmizləndi';
$messages['folderexpunged'] = 'Qovluq uğurla sıxıldı';
$messages['deletedsuccessfully'] = 'Silindi';
$messages['converting'] = 'Məktubun formatlaşması silinir...';
$messages['messageopenerror'] = 'Məktubu serverdən yükləmək alınmır';
$messages['fileuploaderror'] = 'Fayl yüklənilmədi';
$messages['filesizeerror'] = 'Yüklənilən fayl maksimal ölçüdən çoxdur - $size';
$messages['copysuccess'] = '$nr kontaktlar uğurlar kopyalanmışdır.';
$messages['movesuccess'] = '$nr kontaktlar uğurla köçürülmüşdür.';
$messages['copyerror'] = 'Heç bir kontaktı kopyalamaq olmur.';
$messages['moveerror'] = 'Heç bir kontaktı köçürmək alınmır.';
$messages['sourceisreadonly'] = 'Verilən ünvanlar mənbəyi yalnız oxunmaq üçün';
$messages['errorsavingcontact'] = 'Əlaqəni ünvanda saxlamaq mümkün deyil';
$messages['movingmessage'] = 'Məktub köçürülür...';
$messages['copyingmessage'] = 'Məktub kopyalanır...';
$messages['copyingcontact'] = 'Kontakt(lar)ın kopyalanması...';
$messages['movingcontact'] = 'Kontak(lar)ın köçürülməsi...';
$messages['deletingmessage'] = 'Məktub(lar) silinir...';
$messages['markingmessage'] = 'Məktub(lar) işarələnir...';
$messages['addingmember'] = 'Kontakt(lar)ın qrupa əlavə edilməsi...';
$messages['removingmember'] = 'Kontakt(lar)ın qrupdan silinməsi...';
$messages['receiptsent'] = 'Oxunulma haqda bildiriş göndərildi';
$messages['errorsendingreceipt'] = 'Oxunulma haqda bildiriş göndərilmədi';
$messages['deleteidentityconfirm'] = 'İdentifikasiyanı silməkdə əminsiniz?';
$messages['nodeletelastidentity'] = 'Siz bu kimliyi silə bilməzsiniz. Bu axırıncıdır.';
$messages['forbiddencharacter'] = 'Qovlu adı qadağan olunmuş simvollar təşkil edir';
$messages['selectimportfile'] = 'Yüklənilən faylı seçin';
$messages['addresswriterror'] = 'Seçilmiş ünvan kitabçası yaddaşa yazıla bilməz';
$messages['contactaddedtogroup'] = 'Ünvanlar qrupa əlavə edildi';
$messages['contactremovedfromgroup'] = 'Ünvanlar qrupdan silindi';
$messages['nogroupassignmentschanged'] = 'Qruplar arası bölgü dəyişməyib.';
$messages['importwait'] = 'İdxal gedir, lütfən gözləyin...';
$messages['importformaterror'] = 'İdxal xətası. Yüklənilən fayl naməlum məlumat formatına malikdir.';
$messages['importconfirm'] = '<b>$inserted ünvanlar müvəffəqiyyətlə idxal edildi, mövcud $skipped buraxılıb</b>:<p><em>$names</em></p>';
$messages['importconfirmskipped'] = '<b>Buraxılmış $skipped mövcud daxillər</b>';
$messages['importmessagesuccess'] = '$nr məktublar uğurla idxal edildi';
$messages['importmessageerror'] = 'İdxal alınmadı! Yüklənilmiş fayl düzgün məktub və ya poçt faylı deyil';
$messages['opnotpermitted'] = 'Əməliyyat qadağandır!';
$messages['httpreceivedencrypterror'] = 'Serverdə qaçıımaz xəta baş verib. Təcili öz inzibatçınız ilə əlaqə qurun. <b>Sizin məktub göndərilməyə bilər.</b>';
$messages['smtpconnerror'] = 'SMTP Error ($code): Serverlə bağlantı alınmadı';
$messages['smtpautherror'] = 'SMTP Error ($code): İdentifikasiya xətası';
$messages['smtpfromerror'] = 'SMTP Error ($code): Göndərəni səlavə etmək mümkün deyil - "$from" ($msg)';
$messages['smtptoerror'] = 'SMTP Error ($code): Qəbul edəni əlavə etmək mümkün deyil - "$to" ($msg)';
$messages['smtprecipientserror'] = 'SMTP Error ($code): Qəbul edənlərin siyahısını emal etmək mümkün deyil';
$messages['smtperror'] = 'SMTP Error ($code): $msg';
$messages['toomanyrecipients'] = 'Qəbul edənlər həddindən artıq çoxdur. Lütfən, $max qədər azaldın.';
$messages['maxgroupmembersreached'] = 'Qrupun ölçüsü imkan verilən maksimumdan artıqdır - $max';
$messages['internalerror'] = 'Daxili xəta. Lütfən bir daha cəhd edin.';
$messages['contactdelerror'] = 'Kontak(lar)ı silmək alınmadı';
$messages['contactdeleted'] = 'Kontak(lar) uğurla silindi';
$messages['contactrestoreerror'] = 'Silinmiş kontakt(lar)ın bərpası alınmadı';
$messages['contactrestored'] = 'Kontakt(lar) bərpa edildi.';
$messages['groupdeleted'] = 'Qrup silindi';
$messages['grouprenamed'] = 'Qrupun adı dəyişdirildi';
$messages['groupcreated'] = 'Qrup yaradıldı';
$messages['savedsearchdeleted'] = 'Saxlanılmış sorğu silindi.';
$messages['savedsearchdeleteerror'] = 'Saxlanılmış sorğunu silmək alınmadı.';
$messages['savedsearchcreated'] = 'Saxlanılmış sorğu yaradıldı.';
$messages['savedsearchcreateerror'] = 'Saxlanılmış sorğunu yaratmaq alınmadı';
$messages['messagedeleted'] = 'Məktub(lar) uğurla silindi';
$messages['messagemoved'] = 'Məktub(lar) uğurla köçürüldü';
$messages['messagecopied'] = 'Məktub(lar) uğurla kopyalandı';
$messages['messagemarked'] = 'Məktub(lar) uğurla işarələndi';
$messages['autocompletechars'] = 'Avtokomplektasiya üçün $min işarə daxil edin';
$messages['autocompletemore'] = 'Axtarış çox nəticə çıxardı. Lütfən, dəqiqləşdirin.';
$messages['namecannotbeempty'] = 'Ad boş ola bilməz';
$messages['nametoolong'] = 'Ad çox uzundur';
$messages['folderupdated'] = 'Qovluq yeniləndi';
$messages['foldercreated'] = 'Qovluq yaradıldı';
$messages['invalidimageformat'] = 'Şəkil formatı düzgün deyil';
$messages['mispellingsfound'] = 'Məktubda orfoqrafik səhvlər tapılıb';
$messages['parentnotwritable'] = 'Qovluğu seçilmiş ana qovluğa köçürmək/yaratmaq alınmır. Giriş hüququ yoxdur.';
$messages['messagetoobig'] = 'Məktubun bir hissəsi emal üçün böyükdür.';
$messages['attachmentvalidationerror'] = 'DİQQƏT! Bu qoşma şübhəlidir, çünki məktubda deyilən növlə eyni deyil. Əgər siz göndərə güvənmirsinizsə, brauzerdə bunu açmayın. Tərkibi təhlükəli ola bilər.<br/><br/><em>Expected: $expected; found: $detected</em>';
$messages['noscriptwarning'] = 'Xəbərdarlıq: Bu vebmeyl xidməti Javascript tələb edir! Funksiyanı istifadə etmək üçün lütfən, brauzerinizin ayarlarında Javascript-i yandırın.';
