<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Benachrichtigung im Browser bei neuer Nachricht';
$labels['desktop'] = 'Desktop-Benachrichtigung bei neuer Nachricht';
$labels['sound'] = 'Akustische Meldung bei neuer Nachricht';
$labels['test'] = 'Test';
$labels['title'] = 'Neue E-Mail!';
$labels['body'] = 'Sie haben eine neue Nachricht';
$labels['testbody'] = 'Dies ist eine Testbenachrichtigung';
$labels['desktopdisabled'] = 'Desktop-Benachrichtigungen sind deaktiviert.';
$labels['desktopunsupported'] = 'Ihr Browser unterstützt keine Desktop-Benachrichtigungen.';
$labels['desktoptimeout'] = 'Desktop-Benachrichtigung geschlossen.';
?>
