<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Montri atentigojn de retumilo pri nova mesaĝo';
$labels['desktop'] = 'Montri atentigojn de komputilo pri nova mesaĝo';
$labels['sound'] = 'Ludi sonon por nova mesaĝo';
$labels['test'] = 'Testi';
$labels['title'] = 'Nova retmesaĝo!';
$labels['body'] = 'Vi ricevis novan mesaĝon.';
$labels['testbody'] = 'Tio estas testo pri atentigo.';
$labels['desktopdisabled'] = 'Atentigoj de komputilo estas malŝaltitaj en via retumilo.';
$labels['desktopunsupported'] = 'Via retumilo ne subtenas atentigojn de komputilo.';
?>
