<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Mostrar notificaciones del navegador al recibir un nuevo mensaje';
$labels['desktop'] = 'Mostrar notificaciones de escritorio al recibir un nuevo mensaje';
$labels['sound'] = 'Reproducir sonido al recibir un nuevo mensaje';
$labels['test'] = 'Prueba';
$labels['title'] = '¡Mensaje nuevo!';
$labels['body'] = 'Ha recibido un mensaje nuevo.';
$labels['testbody'] = 'Esta es una notificación de prueba.';
$labels['desktopdisabled'] = 'Las notificaciones de escritorio están deshabilitadas en su navegador.';
$labels['desktopunsupported'] = 'Su navegador no soporta notificaciones de escritorio.';
$labels['desktoptimeout'] = 'Cerrar notificación de escritorio';
?>
