<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'نمایش تذکرهای مرورگر برای پیغام جدید';
$labels['desktop'] = 'نمایش تذکرهای رومیزی برای پیغام جدید';
$labels['sound'] = 'پخش صدا برای پیغام جدید';
$labels['test'] = 'آزمایش';
$labels['title'] = 'رایانامه‌ی جدید!';
$labels['body'] = 'شما یک پیغام جدید دریافت کرده‌اید.';
$labels['testbody'] = 'این یک تذکر آزمایشی است.';
$labels['desktopdisabled'] = 'تذکرهای رومیزی در مرورگر شما غیرفعال شده‌اند.';
$labels['desktopunsupported'] = 'مرورگر شما تذکرهای رومیزی را پشتیبانی نمی‌کند.';
$labels['desktoptimeout'] = 'بستن تذکر دسکتاپ';
?>
