<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Näytä selainilmoitus uuden viestin saapuessa';
$labels['desktop'] = 'Näytä työpöytäilmoitus uuden viestin saapuessa';
$labels['sound'] = 'Toista ääni uuden viestin saapuessa';
$labels['test'] = 'Testaa';
$labels['title'] = 'Uutta sähköpostia!';
$labels['body'] = 'Sait uuden viestin.';
$labels['testbody'] = 'Tämä on testi-ilmoitus.';
$labels['desktopdisabled'] = 'Työpöytäilmoitukset on estetty selaimessa.';
$labels['desktopunsupported'] = 'Selaimesi ei tue työpöytäilmoituksia.';
$labels['desktoptimeout'] = 'Sulje työpöytäilmoitus';
?>
