<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Vís kaga kunngerðir tá ið nýtt boð verður stovna';
$labels['desktop'] = 'Vís skrivaraborð kunngerðir tá ið nýtt boð er stovna';
$labels['sound'] = 'Spæl ljóð tá ið nýtt boð verður móttikið';
$labels['test'] = 'Roynd';
$labels['title'] = 'Nýggjur teldupostur!';
$labels['body'] = 'Tú hevur móttikið eini boð.';
$labels['testbody'] = 'Hettar eru eini royndar boð.';
$labels['desktopdisabled'] = 'Skrivaraborð kunngerðir eru sløktar í tínum kaga.';
$labels['desktopunsupported'] = 'Tín kagi studlar ikki skriviborða kunngerðir.';
$labels['desktoptimeout'] = 'Sløkk skriviborða kunngerðir';
?>
