<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Amosar notificacións no navegador cando entre unha mensaxe nova';
$labels['desktop'] = 'Amosar notificacións no escritorio cando chegue unha mensaxe nova';
$labels['sound'] = 'Reproducir un son cando chegue unha nova mensaxe';
$labels['test'] = 'Proba';
$labels['title'] = 'Novo Correo!';
$labels['body'] = 'Recibiches unha nova mensaxe';
$labels['testbody'] = 'Esta é unha notificación de proba';
$labels['desktopdisabled'] = 'As notificacións de escritorio están desactivadas no teu navegador';
$labels['desktopunsupported'] = 'O teu navegador non soporta notificacións de escritorio.';
$labels['desktoptimeout'] = 'Pechar notificación de escritorio';
?>
