<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Értesítés megjelenítése böngészőben amikor új üzenet érkezik';
$labels['desktop'] = 'Értesítés megjelenítése az asztalon amikor új üzenet érkezik';
$labels['sound'] = 'Hang lejátszása új üzenet érkezésekor';
$labels['test'] = 'Próba';
$labels['title'] = 'Új üzenet!';
$labels['body'] = 'Új üzenet érkezett.';
$labels['testbody'] = 'Ez egy értesítési próba.';
$labels['desktopdisabled'] = 'A böngészőben tiltva van az asztali értesítések megjelenítése.';
$labels['desktopunsupported'] = 'A böngésző nem támogatja az asztali értesítések megjelenítését.';
$labels['desktoptimeout'] = 'Az értesítés bezárása';
?>
