<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Presentar notificationes de navigator quando un nove message arriva';
$labels['desktop'] = 'Presentar notificationes de scriptorio quando un nove message arriva';
$labels['sound'] = 'Facer sonar un sono quando un nove message arriva';
$labels['test'] = 'Test';
$labels['title'] = 'Nove e-mail!';
$labels['body'] = 'Vos ha recipite un nove message.';
$labels['testbody'] = 'Iste es un notification de test.';
$labels['desktopdisabled'] = 'Le notificationes de scriptorio ha essite disactivate in vostre navigator.';
$labels['desktopunsupported'] = 'Vostre navigator non supporta le notificationes de scriptorio.';
$labels['desktoptimeout'] = 'Clauder notification de scriptorio';
?>
