<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Agahdariyên gerokê li ser peyama nû bide nîşan';
$labels['desktop'] = 'Agahdariyên sermasê li ser peyama nû bide nîşan';
$labels['sound'] = 'Deng li ser peyameke nû veke';
$labels['test'] = 'Test';
$labels['title'] = 'Emaila Nû!';
$labels['body'] = 'Peyameke te ya nû heye.';
$labels['testbody'] = 'Ev agahdariyeke testê ye.';
$labels['desktopdisabled'] = 'Agahdariyên sermasê di geroka te de girtî ne. ';
$labels['desktopunsupported'] = 'Geroka te bi agahdariyên sermasê re ne ahengdar e.';
$labels['desktoptimeout'] = 'Ahahadariya sermasê bigire';
?>
