<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Vis varsel i nettleseren ved ny melding';
$labels['desktop'] = 'Vis varsel på skrivebordet ved ny melding';
$labels['sound'] = 'Spill av lyd ved ny melding';
$labels['test'] = 'Test';
$labels['title'] = 'Ny e-post!';
$labels['body'] = 'Du har mottatt en ny melding';
$labels['testbody'] = 'Dette er et testvarsel.';
$labels['desktopdisabled'] = 'Skrivebordsvarsel er slått av i din nettleser.';
$labels['desktopunsupported'] = 'Din nettleser støtter ikke visning av varsel på skrivebordet.';
$labels['desktoptimeout'] = 'Lukk skrivebordsvarsling';
?>
