<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Toon melding in browser bij nieuw bericht';
$labels['desktop'] = 'Toon melding op bureaublad bij nieuw bericht';
$labels['sound'] = 'Geluid afspelen bij nieuw bericht';
$labels['test'] = 'Test';
$labels['title'] = 'Nieuwe e-mail!';
$labels['body'] = 'U heeft een nieuw bericht ontvangen.';
$labels['testbody'] = 'Dit is een testmelding.';
$labels['desktopdisabled'] = 'Bureaubladmeldingen zijn uitgeschakeld in uw browser.';
$labels['desktopunsupported'] = 'Uw browser ondersteunt geen bureaubladmeldingen.';
$labels['desktoptimeout'] = 'Sluit bureaubladmelding';
?>
