<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Exibir notificação quando uma nova mensagem chegar';
$labels['desktop'] = 'Exibir notificação no desktop quando uma nova mensagem chegar';
$labels['sound'] = 'Alerta sonoro quando uma nova mensagem chegar';
$labels['test'] = 'Testar';
$labels['title'] = 'Novo Email!';
$labels['body'] = 'Você recebeu uma nova mensagem.';
$labels['testbody'] = 'Essa é uma notificação de teste.';
$labels['desktopdisabled'] = 'As notificações no desktop estão desabilitadas no seu navegador.';
$labels['desktopunsupported'] = 'Seu navegador não suporta notificações no desktop';
$labels['desktoptimeout'] = 'Fechar notificação';
?>
