<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Zobraziť upozornenie v prehliadači pri novej správe';
$labels['desktop'] = 'Zobraziť upozornenie na ploche pri novej správe';
$labels['sound'] = 'Prehrať zvuk pri novej správe';
$labels['test'] = 'Otestovať';
$labels['title'] = 'Nová správa!';
$labels['body'] = 'Máte novú správu.';
$labels['testbody'] = 'Toto je skúšobné upozornenie.';
$labels['desktopdisabled'] = 'Upozornenia na ploche sú vo vašom prehliadači vypnuté.';
$labels['desktopunsupported'] = 'Váš prehliadač nepodporuje upozornenia na ploche.';
$labels['desktoptimeout'] = 'Zatvoriť notifikáciu na ploche';
?>
