<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Prikaži obvestilo za nova sporočila';
$labels['desktop'] = 'Prikaži obvestila na namizju za vsa nova sporočila';
$labels['sound'] = 'Ob novem sporočilu predvajaj zvok';
$labels['test'] = 'Test';
$labels['title'] = 'Novo sporočilo';
$labels['body'] = 'Prejeli ste novo sporočilo.';
$labels['testbody'] = 'To je testno obvestilo.';
$labels['desktopdisabled'] = 'Obvestila na namizju so v vašem brskalniku onemogočena.';
$labels['desktopunsupported'] = 'Vaš brskalnik ne podpira izpis obvestil na namizju.';
$labels['desktoptimeout'] = 'Zapri obvestila na namizju';
?>
