<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Avisera nytt meddelande i webbläsaren';
$labels['desktop'] = 'Avisera nytt meddelande på skrivbordet';
$labels['sound'] = 'Avisera nytt meddelande med ljudsignal';
$labels['test'] = 'Prova';
$labels['title'] = 'Nytt meddelande!';
$labels['body'] = 'Du har mottagit ett nytt meddelande.';
$labels['testbody'] = 'Denna avisering är ett prov.';
$labels['desktopdisabled'] = 'Avisering på skrivbordet är avstängt i webbläsaren.';
$labels['desktopunsupported'] = 'Avisering på skrivbordet stöds inte av webbläsaren.';
$labels['desktoptimeout'] = 'Stäng avisering på skrivbordet';
?>
