<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = 'Yeni iletiler web tarayıcıdan bildirilsin';
$labels['desktop'] = 'Yeni iletiler Masaüstünden bildirilsin';
$labels['sound'] = 'Yeni ileti geldiğinde ses çalınsın';
$labels['test'] = 'Deneme';
$labels['title'] = 'Yeni İleti!';
$labels['body'] = 'Yeni bir iletiniz var.';
$labels['testbody'] = 'Bu bir test bildirimidir.';
$labels['desktopdisabled'] = 'Web tarayıcınızda masaüstü bildirimi devre dışı bırakıldı.';
$labels['desktopunsupported'] = 'Web tarayıcınız masaüstü bildirimleri desteklemiyor';
$labels['desktoptimeout'] = 'Masaüstü bildirimini kapat';
?>
