<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/newmail_notifier/localization/<lang>.inc                      |
 |                                                                       |
 | Localization file of the Roundcube Webmail New Mail Notifier plugin   |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-newmail_notifier/
*/
$labels['basic'] = '在浏览器中显示新邮件提醒';
$labels['desktop'] = '在桌面显示新邮件提醒';
$labels['sound'] = '收到新邮件时播放声音';
$labels['test'] = '测试';
$labels['title'] = '您收到一封新邮件!';
$labels['body'] = '您收到一封新邮件。';
$labels['testbody'] = '这是一个提醒测试。';
$labels['desktopdisabled'] = '您的浏览器已禁止桌面提醒功能。';
$labels['desktopunsupported'] = '您的浏览器不支持桌面提醒功能。';
$labels['desktoptimeout'] = '关闭桌面通知';
?>
