<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/zipdownload/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 | Copyright (C) 2012-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/
$labels['downloadall'] = '모든 첨부파일을 다운로드';
$labels['download'] = '다운로드...';
$labels['downloadmbox'] = 'Mbox 형식(.zip)';
$labels['downloadmaildir'] = 'Maildir 형식(.zip)';
$labels['downloademl'] = '소스(.eml)';
