<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/zipdownload/localization/<lang>.inc                           |
 |                                                                       |
 | Localization file of the Roundcube Webmail Zipdownload plugin         |
 | Copyright (C) 2012-2014, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-zipdownload/
*/
$labels['downloadall'] = 'എല്ലാ അറ്റാച്ച്മെന്റുകളും ഡൗൺലോഡ് ചെയ്യുക';
$labels['download'] = 'ഡൗൺലോഡ്...';
$labels['downloadmbox'] = 'എംബോക്സ് രീതി (.zip)';
$labels['downloadmaildir'] = 'മെയിൽഡിർ രീതി (.zip)';
$labels['downloademl'] = 'സ്രോതസ്സ് (.eml)';
