name: Create PR to merge to nightly from staging
on:
  push:
    branches:
      - staging
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run the Action
        if: startsWith(github.ref, 'refs/heads/feature')
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: Automatic PR to nightly from ${{ github.event.repository.updated_at}}
          assignee: DerLinkman
          reviewer: DerLinkman
          label: upstream
          new_string: ${{ github.event.commits[0].message }}
          get_diff: true