<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'الأرشيف';
$labels['buttontitle'] = 'أرشف هذه الرسالة';
$labels['archived'] = 'أُرشفت بنجاح';
$labels['archivedreload'] = 'ارشفت بنجاح. اعد تحميل الصفحه لاضهار الملف المؤرشف';
$labels['archiveerror'] = 'بعض الرسائل لايمكن ارشفتها';
$labels['archivefolder'] = 'الأرشيف';
$labels['settingstitle'] = 'الأرشيف';
$labels['archivetype'] = 'تقسيم الأرشيف ب';
$labels['archivetypeyear'] = 'السنة (مثال. الارشيف/2012)';
$labels['archivetypemonth'] = 'الشهر (مثال. الارشيف/2012/06)';
$labels['archivetypefolder'] = 'المجلد الاصلي';
$labels['archivetypesender'] = 'ايميل المرسل';
$labels['unkownsender'] = 'مجهول';
?>
