<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Архіў';
$labels['buttontitle'] = 'Перанесці ў архіў';
$labels['archived'] = 'Перанесена ў архіў';
$labels['archivedreload'] = 'Перанесена ў архіў. Перагрузіце старонку, каб пабачыць новыя архіўныя папкі.';
$labels['archiveerror'] = 'Некаторыя паведамленні не могуць быць перанесены ў архіў';
$labels['archivefolder'] = 'Архіў';
$labels['settingstitle'] = 'Архіў';
$labels['archivetype'] = 'Раздзяліць архіў паводле';
$labels['archivetypeyear'] = 'года (прыкладам, Архіў/2012)';
$labels['archivetypemonth'] = 'месяца (прыкладам, Архіў/2012/06)';
$labels['archivetypefolder'] = 'Выточная папка';
$labels['archivetypesender'] = 'Эл. пошта адпраўніка';
$labels['unkownsender'] = 'невядомы';
?>
