<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Arhiva';
$labels['buttontitle'] = 'Arhiviraj ovu poruku';
$labels['archived'] = 'Arhiviranje uspješno';
$labels['archivedreload'] = 'Uspješno arhivirano. Ponovo učitajte stranicu da biste vidjeli nove foldere za arhiviranje.';
$labels['archiveerror'] = 'Neke poruke nisu mogle biti arhivirane';
$labels['archivefolder'] = 'Arhiva';
$labels['settingstitle'] = 'Arhiva';
$labels['archivetype'] = 'Podijeli arhivu po';
$labels['archivetypeyear'] = 'Godinama (npr. Arhiva/2012)';
$labels['archivetypemonth'] = 'Mjesecima (npr Arhiva/2012/06)';
$labels['archivetypefolder'] = 'Originalni folder';
$labels['archivetypesender'] = 'Email pošiljaoca';
$labels['unkownsender'] = 'nepoznato';
?>
