<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Archif';
$labels['buttontitle'] = 'Archifo\'r neges hwn';
$labels['archived'] = 'Archifwyd yn llwyddiannus';
$labels['archivedreload'] = 'Archifwyd yn llwyddiannus. Ail-lwythwch y dudalen i weld ffolderi archif newydd.';
$labels['archiveerror'] = 'Nid oedd yn bosib archifo rhai negeseuon';
$labels['archivefolder'] = 'Archif';
$labels['settingstitle'] = 'Archif';
$labels['archivetype'] = 'Rhannu archif gyda';
$labels['archivetypeyear'] = 'Blwyddyn (e.g. Archif/2012)';
$labels['archivetypemonth'] = 'Mis (e.g. Archif/2012/06)';
$labels['archivetypefolder'] = 'Ffolder gwreiddiol';
$labels['archivetypesender'] = 'Ebost anfonwr';
$labels['unkownsender'] = 'anhysbys';
$labels['readonarchive'] = 'Nodi\'r neges fel darllenwyd ar archif';
?>
