<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Arkiv';
$labels['buttontitle'] = 'Arkivér denne besked';
$labels['archived'] = 'Succesfuldt arkiveret.';
$labels['archivedreload'] = 'Arkivering lykkedes. Genindlæs siden for at se den nye arkiv mappe.';
$labels['archiveerror'] = 'Nogle meddelelser kunne ikke arkiveres';
$labels['archivefolder'] = 'Arkiv';
$labels['settingstitle'] = 'Arkiver';
$labels['archivetype'] = 'Del arkiv med';
$labels['archivetypeyear'] = 'År (f.eks. Arkiv/2012)';
$labels['archivetypemonth'] = 'Måned (f.eks. Arkiv/2012/06)';
$labels['archivetypefolder'] = 'Original mappe';
$labels['archivetypesender'] = 'Afsenders email';
$labels['unkownsender'] = 'ukendt';
$labels['readonarchive'] = 'Marker denne meddelelse som læst i arkivet';
?>
