<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Gorde';
$labels['buttontitle'] = 'Gorde mezu hau';
$labels['archived'] = 'Ongi gorde da';
$labels['archivedreload'] = 'Ongi gorde da. Freskatu orria fitxategi-karpeta berria ikusteko.';
$labels['archiveerror'] = 'Mezu batzuk ezin dira gorde.';
$labels['archivefolder'] = 'Gorde';
$labels['settingstitle'] = 'Gorde';
$labels['archivetype'] = 'Banatu honen arabera';
$labels['archivetypeyear'] = 'Urtea (e.b. Archive/2012)';
$labels['archivetypemonth'] = 'Hilabete (e.b. Archive/2012/06)';
$labels['archivetypefolder'] = 'Jatorrizko karpeta';
$labels['archivetypesender'] = 'Bidaltzailearen helbidea';
$labels['unkownsender'] = 'ezezaguna';
?>
