<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Archiver';
$labels['buttontitle'] = 'Archiver ce courriel';
$labels['archived'] = 'Archivé avec succès';
$labels['archivedreload'] = 'Archivé avec succès. Recharger la page pour voir les nouveaux dossiers d\'archives.';
$labels['archiveerror'] = 'Certains courriels n\'ont pas pu être archivés.';
$labels['archivefolder'] = 'Archiver';
$labels['settingstitle'] = 'Archiver';
$labels['archivetype'] = 'Diviser l\'archive par';
$labels['archivetypeyear'] = 'Année (ex. Archives/2012)';
$labels['archivetypemonth'] = 'Mois (ex. Archives/2012/06)';
$labels['archivetypefolder'] = 'Dossier original';
$labels['archivetypesender'] = 'Courriel de l\'expéditeur';
$labels['unkownsender'] = 'inconnu';
$labels['readonarchive'] = 'Marquer le courriel comme lu lors de l\'archivage';
?>
