<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'ארכיון';
$labels['buttontitle'] = 'משלוח ההודעה לארכיב';
$labels['archived'] = 'עדכון הארכיון הצליח';
$labels['archivedreload'] = 'נשמר בהצלחה בארכיב. יש לרענו את הדף כדי לראות את התיקיות החדשות בארכיב.';
$labels['archiveerror'] = 'לא ניתן היה להעביר לארכיב חלק מההודעות';
$labels['archivefolder'] = 'ארכיון';
$labels['settingstitle'] = 'ארכיב';
$labels['archivetype'] = 'לחלק את הארכיב על ידי';
$labels['archivetypeyear'] = 'שנה ( לדוגמה, ארכיב/2012/96 )';
$labels['archivetypemonth'] = 'חודש ( לדוגמה, ארכיב/2012/96 )';
$labels['archivetypefolder'] = 'תיקיה מקורית';
$labels['archivetypesender'] = 'שולח ההודעה';
$labels['unkownsender'] = 'לא ידוע';
$labels['readonarchive'] = 'יש לסמן את ההודעה בארכיב כאילו נקראה';
?>
