<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Архив';
$labels['buttontitle'] = 'Энэ зурвасыг архивлах';
$labels['archived'] = 'Амжилттай архивлагдлаа';
$labels['archivedreload'] = 'Амжилттай архивлагдлаа. Хуудсыг дахин дуудаж шинэ үүссэн архив хавтсыг харна уу.';
$labels['archiveerror'] = 'Зарим зурвас архивлагдаж чадахгүй';
$labels['archivefolder'] = 'Архив';
$labels['settingstitle'] = 'Архив';
$labels['archivetype'] = 'Архивыг дараахаар ялга: ';
$labels['archivetypeyear'] = 'Он (жиш: Архив/2012)';
$labels['archivetypemonth'] = 'Сар (жиш: Архив/2012/06)';
$labels['archivetypefolder'] = 'Жинхэнэ хавтас';
$labels['archivetypesender'] = 'Илгээгчийн мэйл хаяг';
$labels['unkownsender'] = 'мэдэгдэхгүй';
?>
