<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Arkiver';
$labels['buttontitle'] = 'Arkiver meldinga';
$labels['archived'] = 'Arkivert';
$labels['archivedreload'] = 'Arkivering vellukka. Last inn sida på nytt for å sjå dei nye arkivmappene.';
$labels['archiveerror'] = 'Nokre meldingar kunne ikkje arkiverast';
$labels['archivefolder'] = 'Arkiver';
$labels['settingstitle'] = 'Arkiv';
$labels['archivetype'] = 'Del arkiv etter';
$labels['archivetypeyear'] = 'År (f.eks. Arkiv/2012)';
$labels['archivetypemonth'] = 'Månad (f.eks. Arkiv/2012/06)';
$labels['archivetypefolder'] = 'Opprinneleg mappe';
$labels['archivetypesender'] = 'Avsendar';
$labels['unkownsender'] = 'ukjent';
?>
