<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Arquivo';
$labels['buttontitle'] = 'Arquivar esta mensagem';
$labels['archived'] = 'Arquivada com sucesso';
$labels['archivedreload'] = 'Arquivado com sucesso. Recarregue a página para ver as novas pastas de arquivo.';
$labels['archiveerror'] = 'Algumas mensagens não puderam ser arquivadas';
$labels['archivefolder'] = 'Arquivo';
$labels['settingstitle'] = 'Arquivo';
$labels['archivetype'] = 'Dividir arquivo por';
$labels['archivetypeyear'] = 'Ano (isto é, Arquivo/2012)';
$labels['archivetypemonth'] = 'Mês (isto é, Arquivo/2012/06)';
$labels['archivetypefolder'] = 'Pasta original';
$labels['archivetypesender'] = 'E-mail do remetente';
$labels['unkownsender'] = 'desconhecido';
$labels['readonarchive'] = 'Marcar a mensagem como lida ao arquivar';
?>
