<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = 'Lưu trữ';
$labels['buttontitle'] = 'Lưu lại bức thư này';
$labels['archived'] = 'Lưu lại thành công';
$labels['archivedreload'] = 'Đã lưu thành công. Tải lại trang này để thấy các thư mục lưu trữ mới.';
$labels['archiveerror'] = 'Một số thư không thể lưu lại được';
$labels['archivefolder'] = 'Lưu trữ';
$labels['settingstitle'] = 'Lưu trữ';
$labels['archivetype'] = 'Chia bộ lưu trữ bởi';
$labels['archivetypeyear'] = 'Năm (ví dụ: Lưu trữ/2012)';
$labels['archivetypemonth'] = 'Tháng (ví dụ: Lưu trữ/2012/06)';
$labels['archivetypefolder'] = 'Thư mục nguyên gốc';
$labels['archivetypesender'] = 'Địa chỉ thư điện tử của người gửi';
$labels['unkownsender'] = 'Không rõ';
?>
