<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/archive/localization/<lang>.inc                                |
 |                                                                       |
 | Localization file of the Roundcube Webmail Archive plugin             |
 | Copyright (C) 2016, The Roundcube Dev Team                            |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-archive/
*/
$labels['buttontext'] = '封存';
$labels['buttontitle'] = '封存此信件';
$labels['archived'] = '已成功封存';
$labels['archivedreload'] = '封存動作完成.重新載入頁面瀏覽新的封存資料夾';
$labels['archiveerror'] = '部分資訊無法完成封存';
$labels['archivefolder'] = '封存';
$labels['settingstitle'] = '封存';
$labels['archivetype'] = '封存檔案切割方式';
$labels['archivetypeyear'] = '年分(例如: 封存/2012)';
$labels['archivetypemonth'] = '月份(例如: 封存/2012/06)';
$labels['archivetypefolder'] = '原始資料夾';
$labels['archivetypesender'] = '寄件者電子信箱';
$labels['unkownsender'] = '未知';
?>
