<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/hide_blockquote/localization/<lang>.inc                       |
 |                                                                       |
 | Localization file of the Roundcube Webmail Hide-Blockquote plugin     |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-hide_blockquote/
*/
$labels['hide'] = 'മറയ്ക്കുക';
$labels['show'] = 'പ്രദർശിപ്പിക്കുക';
$labels['quotelimit'] = 'ഇതിലും കൂടുതലാണ് വരികളുടെ എണ്ണമെങ്കിൽ അവലംബം മറയ്ക്കുക';
?>
