<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/hide_blockquote/localization/<lang>.inc                       |
 |                                                                       |
 | Localization file of the Roundcube Webmail Hide-Blockquote plugin     |
 | Copyright (C) 2012-2013, The Roundcube Dev Team                       |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

 For translation see https://www.transifex.com/projects/p/roundcube-webmail/resource/plugin-hide_blockquote/
*/
$labels['hide'] = '隐藏';
$labels['show'] = '显示';
$labels['quotelimit'] = '隐藏引用当行数大于';
?>
